### ISSUE TITLE
Atom RegExp Highlighting Inaccuracies 

### ISSUE THREAD

**Issue by austincrft** [MagicStack/MagicPython#1]
Noticed some inaccuracies in the Python raw strings in Atom. Not sure if they exist in Sublime. The links above the images will take you to the file for more context.

[gherkin_event_listener.py](https://github.com/austincrft/sublime-gherkin-auto-complete-plus/blob/master/gherkin_event_listener.py)
![image](https://cloud.githubusercontent.com/assets/3616544/10519153/294ed04c-732a-11e5-87b5-583ff8e3ce1e.png)

[update_steps.py](https://github.com/austincrft/sublime-gherkin-auto-complete-plus/blob/master/update_steps.py)
![image](https://cloud.githubusercontent.com/assets/3616544/10519212/718c8aca-732a-11e5-88ff-61972740f807.png)

Looks like they're failing at the first apostrophe after a raw string.

**Comment by austincrft** [comment]
Not sure if this is a bug or feature request to get RegExp highlighting in raw strings.

**Comment by 1st1** [comment]
Hi @austincrft, thanks for the bug report!  What version of MagicPython in Atom are you using?  We were reworking how regexes are implemented, here's what I'm seeing with 0.4.6:

<img width="555" alt="screen shot 2015-10-15 at 11 57 00 am" src="https://cloud.githubusercontent.com/assets/239003/10519471/e10af9e6-7333-11e5-8ad7-e8d4566d7abf.png">

<img width="642" alt="screen shot 2015-10-15 at 11 55 49 am" src="https://cloud.githubusercontent.com/assets/239003/10519478/e797fe3a-7333-11e5-9680-bde110d1ab8a.png">

**Comment by austincrft** [comment]
Awesome! Thanks for the great plugin! :smile:

**Comment by 1st1** [comment]
Great! Should I close the issue?

**Comment by austincrft** [comment]
Sounds good to me!
