### ISSUE TITLE
Incorrect highlighting for print [] in python 2.7

### ISSUE THREAD

**Issue by M4urice** [MagicStack/MagicPython#10]
the print keyword isn't highlighted if it is followed by a list:

`print [1, 2, 3]`

Python 2.7 only ofc.

***Edit 20.10.15:***

same goes for the `unicode` keyword in general.

**Comment by 1st1** [comment]
>  the print keyword isn't highlighted if it is followed by a list:

This is now fixed in v0.4.24. If you're using Atom you can update the package now, if you're on ST -- it will be pushed to Package Control soon.

**Comment by 1st1** [comment]
> same goes for the unicode keyword in general.

We don't highlight Python 2 built-in names that didn't make it to Python 3 :(

**Comment by 1st1** [comment]
We might want to assign some special scope for Python2-only builtins though.

**Comment by M4urice** [comment]
Probably a good idea if you want to support Python2 as well (since this project aims to replace the default highlighter).

Maybe you want to open a new issue for this? 

Also check out this list: https://docs.python.org/2/library/2to3.html

**Comment by 1st1** [comment]
> Maybe you want to open a new issue for this?
