### ISSUE TITLE
Faulty syntax highlighting for Py3.6's f-strings.

### ISSUE THREAD

**Issue by s-c-p** [MagicStack/MagicPython#103]
* **Editor name and version**: Sublime Text Version 3.0 Build 3143
* **Platform**: Linux ubuntu-gnome 4.10.0-28-generic #32~16.04.2-Ubuntu SMP ... x86_64 x86_64 x86_64 GNU/Linux
* **Color scheme**: aristocrat (yes, thank you)
* **MagicPython version**: [don't know how to locate it, installed it at 23-Sept-2017]
* **A sreenshot**: see below
* **5-10 lines of surrounding code**:

```
	with sqliteDB(dbFile) as cur:
		try:
			# some code that might
			raise sqlite3.IntegrityError
		except sqlite3.IntegrityError:
			# UNIQUE constraint failed
			x = cur.execute("...")
			y = x.fetchall()[0]
			timestamp = y[0]
			humanTime = utils.humanizeTime(timestamp)
			raise RuntimeError(f"File already imported on " \
				"{timestamp}, i.e. {humanTime}"	# here is the faulty highlighting, I expect the variables to look white
			)
		else:
			ans = cur.lastrowid
	return ans
```

Incorrect highlighting screenshot:
![incorrect](https://user-images.githubusercontent.com/26688071/30770091-4ac3c9e6-a017-11e7-9340-3e0cbf1dddc2.png)

The kind of highlighting I expect (but in lines split at 80 chars)
![correct](https://user-images.githubusercontent.com/26688071/30770093-624ec502-a017-11e7-89df-8cfb903865e8.png)

P.S. The reason I did the `f"text"\` followed by `"more text"` on a new line is because I want to submit a patch where they have strict 80 chat-line limit.

**Comment by vpetrovykh** [comment]
You do understand that the 2 strings in your example are *not* equivalent? 

The part of the string `"{timestamp}, i.e. {humanTime}"` is not an f-string, as evidenced by the absence of the `f` prefix.

Try the following snippet in a python3.6 prompt:
```python
a = 42
b = f'prefix' \
 ' {a}'
c = f'other' \
 f' {a}'
print(b)
print(c)
```

**Comment by s-c-p** [comment]
Oh okay, I didn't know that's how Python works, thanks for let me know.

**False alarm**

On a side note would you please share how did you get so good at regex and ast
