### ISSUE TITLE
Dot functions highlight in VS Code?

### ISSUE THREAD

**Issue by ipoznyak** [MagicStack/MagicPython#104]
I'm trying to get it to highlight python code in VS Code the way python code highlighted in Sublime Text 3. Right now in VS Code it doesn't highlight default python dot functions (or whatever you call it). For example: ** print(some_str_variable.title()) ** I expect .title() to be highlighted but it's not.

* **Editor name and version**: VS Code 1.16.1
* **Platform**: macOS
* **Color scheme**: Monokai
* **MagicPython version**: included with VS Code

**Comment by 1st1** [comment]
MagicPython has no way of distinguishing `.title()` called on a `str` object (for which it's a built-in method) from `.title()` called on a user-defined object. Highlighting `.title()` for all kinds of objects would be confusing.

**Comment by farhank3389** [comment]
@1st1 Why would highlighting to for `.title()` for all objects be confusing? This is the way atom does it and it looks much better than white text.

**Comment by cardoso-neto** [comment]
You should at least offer this as an option. smh
