### ISSUE TITLE
Scope `@` in decorators as punctuation

### ISSUE THREAD

**Issue by chbk** [MagicStack/MagicPython#105]
Can `@` have its own scope? It would be handy as `punctuation.definition.decorator`, similarly to `$` scoped as `punctuation.definition.variable` in php for example.

**Comment by elprans** [comment]
`@` is an actual operator in Python 3, so it normally has the `keyword.operator.arithmetic.python` scope.  And in decorators, it is in the `meta.function.decorator.python`, and `entity.name.function.decorator.python` scope together with the decorator name.  IMO, a distinct scope for  `@` in decorators isn't very useful. @vpetrovykh, @1st1?

**Comment by 1st1** [comment]
I'm not opposed to giving `@`a distinct scope when it's a decorator.  Those who want can then highlight it differently.  The proposed `punctuation.definition.decorator` sounds like a good scope name.
