### ISSUE TITLE
Differentiate %-style from other types of string formatting

### ISSUE THREAD

**Issue by jkyeung** [MagicStack/MagicPython#106]
I see there are several issues reported by people that are either confused by or don't like the highlighting for printf-style interpolation. I have read the various explanations why the existing behavior should not be changed, and I think I understand and mostly agree with the reasons.

I also noticed a few mentions that there might be plans to enhance how string formatting is highlighted, so I realize there is a chance that what I'm about to propose (or something like it) is already in the works.

My proposal is to put %-style formatting in its own scope (other than `constant.character.format.placeholder.other.python`), so that people can choose to de-highlight it if they wish, while still maintaining the highlighting for {}-style formatting.

**Comment by chbk** [comment]
I agree. There should be a way to differentiate `%`, `%()` and `{}`.

**Comment by vpetrovykh** [comment]
We could add `meta.format.percent.python` and `meta.format.brace.python` scopes to wrap around percent- and brace-formatting, respectively. This way a specialized highlighter can still be configured to ignore one or the other (or even both) if necessary, but by default they both will remain highlighted as well.

**Comment by vpetrovykh** [comment]
The change is in the master branch and will make it to the next release version.

Scopes `meta.format.percent.python` and `meta.format.brace.python` mark percent- and brace-formatting in strings. This should enable fine tuning the color scheme to hide percent-formatting.

**Comment by vpetrovykh** [comment]
Closing because the scopes have been added and in general Python 3.6 introduced f-strings, which are the preferred way to format strings now.
