### ISSUE TITLE
Class and function names lose scope within parentheses

### ISSUE THREAD

**Issue by jkyeung** [MagicStack/MagicPython#107]
* **Editor name and version**: VS Code 1.16.0, Atom 1.21.1
* **Platform**: Windows 7
* **Color scheme**: highly customized
* **MagicPython version**: 1.0.12 (at least in Atom)

![magicpython - lost function name highlighting](https://user-images.githubusercontent.com/4826859/32028716-0357caec-b9be-11e7-9914-20b987617e96.png)

The scopes for the incorrectly highlighted elements are
* `@`: keyword.operator.arithmetic.python
* `decorator`: source.python
* `bar`: meta.function-call.generic.python

Class names similarly lose their highlighting in this situation.

I realize this behavior could in a way be considered a feature, or at least not a problem, because the *real* issue is the incorrect parentheses, which is the user's fault, not MagicPython's. But other elements are still properly scoped within the parenthesized area, which gives it a weird "is it working or is it not" effect. Also, Atom's included Python highlighter doesn't exhibit this loss of highlighting. (Though of course MagicPython is significantly better overall than that highlighter.)

If the existing behavior is considered desirable or more difficult to fix than it's worth, I can understand that. This is a great project in any case! Thanks for building it!

**Comment by 1st1** [comment]
> If the existing behavior is considered desirable or more difficult to fix than it's worth, I can understand that. 

Yeah. When there's a syntax error, all bets are off.  I recommend to install a Python linter to better highlight problematic areas.  Unfortunately, this is "not a bug" for MagicPython.

> This is a great project in any case! Thanks for building it!

Thanks a lot!
