### ISSUE TITLE
Format string syntax doesn't recognize accepted (but invalid?) field names

### ISSUE THREAD

**Issue by nicktimko** [MagicStack/MagicPython#108]
* **Editor name and version**: VSCode 1.17.2
* **Platform**: OS X 10.12
* **Color scheme**: Monokai
* **MagicPython version**: none/1.0.12 (over top of the one that's baked VS Code)
* **A screenshot (broken?)**:
![screen shot 2017-10-31 at 4 28 38 pm](https://user-images.githubusercontent.com/5297556/32249912-9352e066-be58-11e7-86af-ca99b7bb1c48.png)
* **A screenshot (like what I expect, but my dictionary keys really have dashes)**:
![screen shot 2017-10-31 at 4 28 17 pm](https://user-images.githubusercontent.com/5297556/32249913-9360ad40-be58-11e7-8b4e-b6110dc36ac9.png)
* **equivalent, maybe a more pedantic version if you only want to support this?**
![screen shot 2017-10-31 at 4 33 22 pm](https://user-images.githubusercontent.com/5297556/32250131-53f9a142-be59-11e7-8bbd-5dc5753ace48.png)

Python seems to be happy to string format such things:

```python
>>> '{build-tag}'.format(**{'build-tag': '42'})
'42'
>>> '{build-tag:}'.format(**{'build-tag': '42'})
'42'
>>> '{-^<>;:}'.format(**{'-^<>;': 'things!'})
'things!'
```

It's not a mind-reader/super arbitrary though:
```python
>>> '{build:tag}'.format(**{'build:tag': '42'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'build'
```

* **Fun fact** I forgot why I called it `ham_auth`. Maybe I was hungry. 🍖 

This might just be a bug/undocumented behavior in Python. The [format string syntax](https://docs.python.org/3/library/string.html#format-string-syntax) claims it only allows identifiers or integers, and the thing with a dash is neither.

```
replacement_field ::=  "{" [field_name] ["!" conversion] [":" format_spec] "}"
field_name        ::=  arg_name ("." attribute_name | "[" element_index "]")*
arg_name          ::=  [identifier | integer]
identifier        ::=  xid_start xid_continue*
id_start          ::=  <all characters in general categories Lu, Ll, Lt, Lm, Lo, Nl, the underscore, and characters with the Other_ID_Start property>
id_continue       ::=  <all characters in id_start, plus characters in the categories Mn, Mc, Nd, Pc and others with the Other_ID_Continue property>
xid_start         ::=  <all characters in id_start whose NFKC normalization is in "id_start xid_continue*">
xid_continue      ::=  <all characters in id_continue whose NFKC normalization is in "id_continue*">
```
I don't quite know what the last ones mean, but "[within the ASCII range](https://docs.python.org/3/reference/lexical_analysis.html#identifiers) (U+0001..U+007F), the valid characters for identifiers are the same as in Python 2.x: the uppercase and lowercase letters A through Z, the underscore _ and, except for the first character, the digits 0 through 9."

**Comment by 1st1** [comment]
I have a feeling that we don't want to highlight undocumented formatting spec.  Other Python interpreters (like PyPy) can chose to support only documented parts of the spec.  @vpetrovykh what do you think?

**Comment by nicktimko** [comment]
Am I mis-reading the spec though? Someone trained in the ways of parsers, EBNF grammar, and characters should drop some truth on this.

**Comment by vpetrovykh** [comment]
Closing because since Python 3.6 introduced f-strings, they are the preferred way to format strings now. Inside f-strings the interpolated value has to be a valid Python expression (which includes variables).
