### ISSUE TITLE
Add support for Python 2 built-in names

### ISSUE THREAD

**Issue by M4urice** [MagicStack/MagicPython#11]
Derived from  #10.

For example the `unicode`keyword.

**Comment by 1st1** [comment]
What color scheme are you using?

For Python 3 built-ins we assign `support.function.builtin.python` scope, and this is how we want it to be.  

We can assign something like `variable.builtin.python2.python` to pyhton2-only builtins, which will make most color schemas highlight pyhton2 builtins differently from other variables.

cc @vpetrovykh

**Comment by M4urice** [comment]
https://github.com/YabataDesign/afterglow-theme

**Comment by 1st1** [comment]
This is how it will look like with `variable.legacy.builtin.python` scope:

<img width="201" alt="screen shot 2015-10-20 at 12 39 35 pm" src="https://cloud.githubusercontent.com/assets/239003/10614335/b02aaa18-7727-11e5-9655-895f54187e57.png">

**Comment by M4urice** [comment]
Looks fine for me! :+1:

**Comment by 1st1** [comment]
Fixed in v0.4.26! Thanks!

**Comment by 1st1** [comment]
(see 67c3322fb43b01d94424a94ba6a0cba2aced6b1c for details)
