### ISSUE TITLE
Problem INstalling on Atom

### ISSUE THREAD

**Issue by vpetrog** [MagicStack/MagicPython#113]
Hello i am experiencing the following issue, that i believe a simple fix can be applied to :)

(node:9077) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

* **atom 1.22.1-1 **:
* **4.13.12-1-ARCH **:
* **Monokai Seti**:
* **1.0.12”**:
![image](https://user-images.githubusercontent.com/24351757/33143755-86f07776-cfc3-11e7-9758-f7c9ee7e939e.png)

**Comment by elprans** [comment]
The failure is not caused be the ``DeprecationWarning``, that one is benign and is triggered by some package outside of MagicPython.   The actual failure is missing `MagicPython/package.json`, which looks like the whole thing failed to download or unpack.  Try removing `.../.atom/packages/MagicPython`, if it exists, and installing again.

**Comment by 1st1** [comment]
Yeah, this doesn't seem to be related to MP. Closing the issue.
