### ISSUE TITLE
Raw string highlighting

### ISSUE THREAD

**Issue by jcrmatos** [MagicStack/MagicPython#114]
**Environment data**

VS Code version: 1.18.1
Python Extension version: 0.80.0
Python Version: CPython 3.5.4 32b
OS and version: Windows 7 Pro SP1 x64

**Actual behavior**

I have the following line

```python
fops.save_txt(environ['SystemRoot'] + r'\explorer.exe '
                      + bdexp.EXPORTS_DIR,
                      bpl.PROGS_TO_LAUNCH_PN)
```

and the r and \e shows in blue with the first ' and xplorer.exe ' shows in brown(?).
My point is that it isn't recognizing it as a string (raw in this case) like it does with the previous 'SystemRoot' which shows all brown(?) and the Intellisense recognizes as a string.

**Expected behavior**

It should show r'\explorer.exe ' all brown(?) and recognize it as a string.

I reported this first in VS Code Python at
`https://github.com/Microsoft/vscode-python/issues/337#issuecomment-349069613`
but Brett Cannon told me to open it here because their syntax highlighting depends on MagicPython.

Thanks,

JM

**Comment by elprans** [comment]
This is a feature.

```python
foo = r'\nregexp'  # this is parsed as a "regexp-string"
bar = R'\nregexp'  # this is parsed as a raw string
```

**Comment by jcrmatos** [comment]
Hello,

I'm sorry but I can't find that difference in the Python spec.
In fact what I find in both Py2 and py3 official docs is:

> Both string and bytes literals may optionally be prefixed with a letter 'r' or 'R'; such strings are called raw strings and treat backslashes as literal characters.
> Unless an 'r' or 'R' prefix is present, escape sequences in string and bytes literals are interpreted according to rules similar to those used by Standard C.

Please reconsider changing MagicPython behavior to be in sync with CPython.

Thanks,

JM

**Comment by jcrmatos** [comment]
Hello,

I forgot to include the CPython official docs links:
`https://docs.python.org/3/reference/lexical_analysis.html`
and
`https://docs.python.org/2/reference/lexical_analysis.html`

Thanks,

JM

**Comment by 1st1** [comment]
> Please reconsider changing MagicPython behavior to be in sync with CPython.

You're correct -- there's no "regex" literal in Python, and `r"string"` is the same thing as `R"string"`.  However, TextMate originally, and Sublime Text later highlighted `r"strings"` as regular expressions for years, and a lot of users expect MagicPython to do the same as it's advertised as a "drop in replacement" of those plugins.  Therefore, unfortunately, we are not going to reconsider having this feature in MagicPython.

**Comment by jcrmatos** [comment]
Hello,

I understand.
Can I ask you please to add a Settings option to disable that behavior?

Thanks,

JM

**Comment by 1st1** [comment]
Generally syntax highlighters don't have settings panels and aren't configurable.  We had an idea how to do that for MP, but don't have time to pursue it.  So unfortunately there's no ETA for this feature.

**Comment by vors** [comment]
This "feature" is super confusing and annoying, please consider dropping it.

**Comment by vors** [comment]
lol, all my comments about the difference in highlighting of r and R strings are now marked as off-topic. I don't see this as off-topic at all (unlike this post - feel free to report it, for sure).

**Comment by memeplex** [comment]
There is a problem with the approach here that was not mentioned: it doesn't play well with the super popular black code formatter, which will turn `R` into `r` again.

**Comment by elprans** [comment]
Black can be told not to do that via `--skip-string-normalization`

**Comment by DiscipleOfEris** [comment]
I'm also coming here from VSCode to report this problem.

I will also mention that literally my *very first experience* with MagicPython (through VSCode) was this non-CPython compliant variation on raw strings. I had to stop coding for a minute to go check the docs to double-check that yes, it was just the syntax highlighter gaslighting me and not me misremembering raw strings.

In my experience, raw strings are extremely common for file system paths. I've obviously also used raw strings for regex, but I'd prefer syntax highlighting on regex to be visibly opt-in than for the syntax highlighter to *incorrectly* assume that raw strings are *always* regex. That said, if the price we pay for getting regex syntax highlighting at all is having to remember that raw strings for non-regex will be incorrectly highlighted, then I suppose there's an argument to be made that it would be worth it. However, I'm sure a comfortable middle ground exists between those two extremes.

**Comment by BBSeward** [comment]
Another user coming here from VSCode and agreeing with the past two comments. Would be great to consider this, or make it an option.

**Comment by nerdfever** [comment]
I do wish this would be re-opened.

For those coming here with the issue - note that using capital R for raw instead of r (R"string" vs. r"string) fixes this problem.

It's a workaround as r vs R has no meaning to Python, but if you use that convention you won't run into this problem.

**Comment by strubbly** [comment]
Sorry, just another VS Code user with the same issue.  We have a company policy to use black with default values everywhere.  That effectively means I can't avoid this incorrect highlighting on raw strings.  So, many of my docstrings are highlighted incorrectly - and the same applies to most of my co-workers. I don't know what would be the best fix but I do think something needs to be done.

**Comment by mitchg17** [comment]
+1 for VS Code confusion

**Comment by pepa-husek** [comment]
the same issue - should definitely be at least configurable if not even turned off by default. yet again conservatism and backward compatibility are hindering normal progress.

**Comment by Jeitan** [comment]
Ditto here. This is still an issue. The rationale that "most users will be confused by making it correct" is no longer valid - rather, the opposite is now happening.  **Most** users are confused by it not recognizing 'r' as a raw string.

**Comment by hutcho** [comment]
Came here after searching why the bug exists in vscode showing \ as escapes on r"" strings. Please add a config option to configure this behaviour. The R"" v r"" differentiation is not a feature, it's a strange design, and needs to be configurable.

**Comment by tylercowdreywadnr** [comment]
I struggled against this issue for a while coming from PyCharm to VSCode. Using some resources found online for editing TokenColorCustimizations and TextMateRules in the JSON settings, I was able to create a custom workaround at the link below. It's annoying having to manually enter hex codes for the colors to all match the way you'd expect inside of an r-string, but unless you are a person who changes themes often you should only have to make the edits once.

Instructions for adding the code to your VSCode user settings are contained in the .txt file here:
https://github.com/tylercowdreywadnr/VSCode_rstring_color_hack

**Comment by vors** [comment]
hi folks! I just came for a moment to say that i'm sorry for the language i used in this thread few years ago. there is no excuse to be rude.

**Comment by scw** [comment]
While there are [specific cases](https://discuss.python.org/t/really-wonky-file-handing/18311/5) where you do need backslash paths on Windows, for most simple path operations you can use forward slashes which avoids the ambiguity with escaping. Just wanted to mention that option since this issue is marked closed and continues to be a point of annoyance for Windows VS Code users in particular.

**Comment by tylercowdreywadnr** [comment]
Agreed @scw . As is often the case, I spent significantly more time creating this workaround to save myself the few seconds changing backslashes to forward slashes each time I copy and paste a folder/file path from windows explorer into VSCode (which I do quite a lot with arcpy scripts). Probably a more elegant way to handle this (e.g. actually packaging my tools for ArcGIS) but over time the ROI on my time/headaches should turn positive hopefully :)

**Comment by fancidev** [comment]
Doesn't feel like a feature to me, but whatever...
