### ISSUE TITLE
Multi-line string erroneously highlighted as comment at '#'-character

### ISSUE THREAD

**Issue by AllanLRH** [MagicStack/MagicPython#117]
* **Sublime Text, Build 3156 (Dev channel)**
* **MAC OS High Sierra**
* **Mariana (Included with Sublime Text; Sublime Linter modified)**
* **MagicPython 1.0.12 (according to `package.json`)**

The multi-line string are erroneously highlighted as a comment after the `#`-character (line 7 in the screenshot). The issue are also present when the string are spanning multiple lines.
And the issue is are also visible on the Github-markdown highlighted string.

<img width="886" alt="screen shot 2017-12-14 at 15 56 03" src="https://user-images.githubusercontent.com/2641327/33998269-57730902-e0e7-11e7-8f00-416d28e3941b.png">

```python
if len(sys.argv) == 1:
    pw_len = 35
else:
    print("Wrong arguments, exiting.", file=sys.stderr)
    sys.exit(1)

char_pool = r'''0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]_{}'''
pwd = ''.join([random.choice(char_pool) for _ in range(pw_len)])

if clipboard:
    pyperclip.copy(pwd)
    print("The new password are placed in the clipboard.")
else:
    print(pwd)
```

**Comment by 1st1** [comment]
This isn't a bug.  MagicPython highlights raw `r'strings'` as regular expressions, and `#` marks the beginning of a one-line comment.

**Comment by elprans** [comment]
If you want the raw string behaviour, use the `R` prefix:
```python
R'''0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]_{}'''
```
