### ISSUE TITLE
Syntax highlighting for docstring fails with PEP 3107 style function return annotation

### ISSUE THREAD

**Issue by VHRanger** [MagicStack/MagicPython#121]
As title says, the syntax highlighting for docstrings fails with PEP 3107 style function return annotation. This propagates bad coloring downstream in the same file.

* **Editor name and version**: VS Code 1.19.1
* **Platform**: Windows 10 x64
* **Color scheme**: Default
* **MagicPython version**: 1.0.12
* **A sreenshot**: 
![magicpython formatting bug](https://user-images.githubusercontent.com/20938940/34531773-6e1ea45a-f081-11e7-90ca-9cf2bdf0407a.png)
* **5-10 lines of surrounding code**:
    def myfunc(firstarg: int = 5, secondarg: list = [1, 2]) -> dict:
    """
    docstring is not highlighted correctly here
    """
        return None

This is because of the "->dict" return annotation.

**Comment by elprans** [comment]
You seem to have some other highlighter installed that overrides MagicPython.

```python
def myfunc(firstarg: int = 5, secondarg: list = [1, 2]) -> dict:
"""
docstring is not highlighted correctly here
"""
return None
```
