### ISSUE TITLE
Highlight improvement about `%d` in the datetime format 

### ISSUE THREAD

**Issue by liangshan** [MagicStack/MagicPython#122]
* **Editor name and version**: VSCode 1.19
* **Platform**: MacOS
* **Color scheme**: Dark+
* **MagicPython version**: Default
* **A sreenshot**: 
![issue](https://user-images.githubusercontent.com/1119114/34701843-5f4ada68-f525-11e7-9103-1456a4b5a503.png)

When `%d` is part of `datetime` format string, i think it should not be highlighted.

**Comment by chbk** [comment]
Imo shouldn't be highlighted at all unless part of a %-string

**Comment by vpetrovykh** [comment]
As has been mentioned in similar issues already, it is not possible to always correctly infer that a particular string is a "datetime format" string.  E.g.:
```python
dt_format = 'The date is: %Y%m%d'
# format output
dt_out = datetime.strftime(datetime.now(), dt_format)

# parse input
my_datetime = datetime.strptime('The date is: 20180719', dt_format)
```

If the code is yours, you can choose to use `r'%Y%m%d'` or `R'%Y%m%d'` to avoid format highlighting. Note that `r'...'` will be highlighted as if it were a regex string, while `R'...'` is a raw string with no frills. 

Additionally, the issue #106 has a proposal that would allow configuring the color scheme to hide `%`-formatting completely (implemented and being reviewed as of this writing).

**Comment by vpetrovykh** [comment]
Python 3.6 introduced f-strings, which are the preferred way to format strings now.

E.g.
```python
# format output directly
dt_out = f'The date is: {datetime.now():%Y%m%d}'

# format output via variable
dt_format = r'%Y%m%d'
dt_out = f'The date is: {datetime.now():{dt_format}}'
```

**Comment by 1st1** [comment]
> Python 3.6 introduced f-strings, which are the preferred way to format strings now.

In fact we should consider dropping support for %s formatting.
