### ISSUE TITLE
Enhancement: Update Atom grammar for tree-sitter

### ISSUE THREAD

**Issue by kylebarron** [MagicStack/MagicPython#128]
A new style of language grammar will be available with Atom 1.25, called [tree-sitter](https://github.com/tree-sitter/tree-sitter). This seems to be more advanced than the current system, [first-mate](https://github.com/atom/first-mate).

It looks like the format for the new syntax rules is currently documented here:
https://github.com/tree-sitter/tree-sitter/blob/master/doc/grammar-schema.json

The current tree-sitter version of Atom's own language-python is here:
https://github.com/atom/language-python/blob/master/grammars/tree-sitter-python.cson

**Comment by 1st1** [comment]
This is highly unlikely to happen in the foreseeable future.  In short, the current grammar works just fine for us and it is working for ST, Atom, and VS Code just fine. It would be a **major** investment for us to rewrite the grammar just for Atom, so unless Atom drops support for ST-style syntaxes we will not even consider this.

**Comment by elprans** [comment]
I agree with @1st1. MagicPython is intended to be used for TextMate-like regexp-based highlighting systems. Reimplementing it as a tree-sitter parser would be a thankless effort since [tree-sitter-python](https://github.com/tree-sitter/tree-sitter-python) already exists.
