### ISSUE TITLE
Incorrect highlight of decorator's opening parenthesis

### ISSUE THREAD

**Issue by playpauseandstop** [MagicStack/MagicPython#13]
I discovered that opening parenthesis in decorator highlighted with wrong color, in my case _(I'm using Tomorrow Night color scheme)_ it highlighted with blue color, when closing parenthesis highlighted with white color

Screenshot for MagicPython decorator highlight

![screen shot 2015-10-20 at 10 27 08 pm](https://cloud.githubusercontent.com/assets/21325/10618698/1871afd4-777a-11e5-8b8c-26febfb1881f.png)

Screenshot for regular Python decorator highlight

![screen shot 2015-10-20 at 10 29 11 pm](https://cloud.githubusercontent.com/assets/21325/10618703/206b3778-777a-11e5-917c-70a0b958a550.png)

**Comment by playpauseandstop** [comment]
And I believe same issue for opening parenthesis of getting dict items,

![screen shot 2015-10-20 at 10 37 40 pm](https://cloud.githubusercontent.com/assets/21325/10618930/6b8fd15e-777b-11e5-8a47-afa799b3594d.png)

**Comment by vpetrovykh** [comment]
Thanks for bringing this to our attention. This is a matter of an overzealous scoping rule. Will fix soon.

**Comment by vpetrovykh** [comment]
As for the dict item access, this should be already [fixed](https://github.com/MagicStack/MagicPython/issues/8).

**Comment by playpauseandstop** [comment]
@vpetrovykh 

Yeah, the issue with dict item access already fixed. Confirmed. Thanks

**Comment by vpetrovykh** [comment]
I've fixed the asymmetrical highlighting for parentheses. This will be part of the next release (soon).

**Comment by vpetrovykh** [comment]
Fixed in v0.4.27 (should be updated in Package Control in a bit). Thanks!
