### ISSUE TITLE
Unpacking Arguments not detected on new lines

### ISSUE THREAD

**Issue by gtalarico** [MagicStack/MagicPython#132]
* **Editor name and version**: VS Code 1.22.2
* **Platform**: MacOs 10.13
* **Color scheme**: Monokai w/ Custom
* **MagicPython version**: The one shipped with VS Code 1.22.2. Commit:
"https://github.com/MagicStack/MagicPython/commit/b453f26ed856c9b16a053517c41207e3a72cc7d5"

## Actual behavior

`keyword.operator.unpacking.arguments.python` is not detected on a new line

## Expected  behavior

Should be detected in new lines

## Steps to reproduce:

```python

some_long_line_________________________________________ = foo('a', 'b', *items, **kwargs)
# In this case, *items is detected properly

some_long_line_________________________________________ = foo('a', 'b'
                                                              *items,
                                                              **kwargs)
# here, both arg and kwargs are not detected properkly

```

# Screenshot
![image](https://user-images.githubusercontent.com/9513968/39338105-d5cbd6e8-498e-11e8-8727-66f6d654321a.png)

# Scope - Correct
![image](https://user-images.githubusercontent.com/9513968/39338115-ee706c90-498e-11e8-9582-cf78342b4179.png)

# Scope - Incorrect
![image](https://user-images.githubusercontent.com/9513968/39338130-00598464-498f-11e8-9cd2-f3af22880550.png)

**Comment by 1st1** [comment]
You're missing a comma in your second example.

**Comment by 1st1** [comment]
A comma before `*items`

**Comment by gtalarico** [comment]
You are right I missed a comma on the example but that was just a terrible coincidence :)
The issue is still present 

![image](https://user-images.githubusercontent.com/9513968/39339764-76d363fe-4998-11e8-9ae8-c647c869f2fe.png)

**Comment by 1st1** [comment]
@vpetrovykh

**Comment by 1st1** [comment]
The fixed version will be released soon!
