### ISSUE TITLE
exec is highlighted as a keyword instead of a builtin

### ISSUE THREAD

**Issue by Beefster09** [MagicStack/MagicPython#134]
This would be correct for Python 2, but given that this is a plugin for 3.latest, this is incorrect behavior.

* **Editor name and version**: Atom 1.27.0 x64
* **Platform**: Windows 10
* **Color scheme**: Any (Atom Dark should work fine)
* **MagicPython version**: 1.0.12
* **5-10 lines of surrounding code**:
```python
    if args.post_ingest is not None:
        code_obj = compile(args.post_ingest, '<snippet>', 'single')
        snippet_logger = logctl.get_logger('<snippet>')
        def post_ingest():
            try:
                exec(code_obj, {'log': snippet_logger}, {})
            except:
                log.exception("Error in --post-ingest snippet")
```

**Comment by 1st1** [comment]
This will be part of the upcoming release.
