### ISSUE TITLE
Feature Request: Add `ipy` filetype

### ISSUE THREAD

**Issue by lzkelley** [MagicStack/MagicPython#137]
Sorry if I'm missing some internal setting somewhere, but can the `ipy` filetype be added to the file types list?  Even if additional syntax highlighting / recognition isn't allowed for ipython magic (`%`) stuff, that's fine.  Thanks!

**Comment by 1st1** [comment]
I'll keep this open to see if more people want this.

**Comment by lzkelley** [comment]
Apparently there isn't much!  It's also trivial to add the following to the `~/.atom/config.cson` file:

```
core:
    customFileTypes:
      "source.python": [
        "ipy"
      ]
```

And everything works perfectly.
