### ISSUE TITLE
[python] syntax highlighting breaks on function annotations

### ISSUE THREAD

**Issue by aeschli** [MagicStack/MagicPython#138]
_From @doug-numetric on July 3, 2018 23:7_

 

- VSCode Version: 1.24.1
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. Create a new file: `test.py`
2. Paste in the following text:
```python3
def test() -> None:
    # Broken comment highlighting
    if True:
        print('The if statement above isn't highlighting either.  Same goes for this string')

```

Does this issue occur when all extensions are disabled?: Yes

Appears to be a regression of: https://github.com/Microsoft/vscode/issues/1467

_Copied from original issue: Microsoft/vscode#53509_

**Comment by aeschli** [comment]
_From @elensar on July 5, 2018 8:25_

I can reproduce this Issue on Windows (Windows 10) too. On Linux (Kubuntu) seems everything fine.

**Comment by 1st1** [comment]
Well, `print('The if statement above isn't highlighting either.  Same goes for this string')` isn't correct Python code.  There's a string `'The if statement above isn'` followed by an invalid sequence of characters `t highlighting either.  Same goes for this string'`.

IOW, `'` in `isn't` isn't escaped, i.e. it should be `isn\'t`.

**Comment by doug-numetric** [comment]
Why was this closed?  I apologize for my typo, but the unescaped apostrophe is *not* the issue.

```python
def test() -> None:
    # Broken comment highlighting
    if True:
        print('The if statement above is not highlighting either.  Same goes for this string')
```
is still broken

**Comment by 1st1** [comment]
Well, GitHub uses MagicPython to highlight Python code, so if there's an actual issue in MP, your snippet in https://github.com/MagicStack/MagicPython/issues/138#issuecomment-403531919 comment should have exposed the bug.  

The fact that the above snippet is highlighted just fine and that I can't reproduce this locally suggests to me that most likely you're not using MP in VSCode, or there's some hiccup in your preferences, or some plugin interferes with MP.

**Comment by 1st1** [comment]
NP!

>  It appears to have been caused by the Python for VSCode 0.2.3 extension

Weird, maybe it's worth filing the issue for Python extension?

**Comment by doug-numetric** [comment]
Yep.  I referenced the parent Microsoft/vscode issue from a related issue in that extension's repo: https://github.com/tht13/Python-vscode/issues/21
