### ISSUE TITLE
Not all arguments highlighted inside of parentheses

### ISSUE THREAD

**Issue by playpauseandstop** [MagicStack/MagicPython#14]
I also discovered that not all arguments highlighted inside of parentheses if comparing with standard Python highlighter

MagicPython

![screen shot 2015-10-20 at 11 19 49 pm](https://cloud.githubusercontent.com/assets/21325/10619976/58b1b9d4-7781-11e5-813e-95fdeaed2acf.png)

Standard Python

![screen shot 2015-10-20 at 11 19 07 pm](https://cloud.githubusercontent.com/assets/21325/10619984/6297e1e4-7781-11e5-810c-07d906989e15.png)

Or this is not a bug, but feature? As constants like `settings.SETTING_NAME` also not highlighted by MagicPython

**Comment by vpetrovykh** [comment]
Yeah, this is a feature. More specifically, we mark all-caps identifiers as `constant.other.caps.python`. I believe your color scheme has a special rule for constants (evidently coloring `constant.other` differently from `constant.numeric`, but the same way as normal code).

**Comment by playpauseandstop** [comment]
Got you, thanks for explanation, closing this as `invalid`
