### ISSUE TITLE
All caps followed by underscore and lowercase text is colored as constant

### ISSUE THREAD

**Issue by Benjamin-Lee** [MagicStack/MagicPython#148]
* **Editor name and version**: Atom 1.28.2
* **Platform**: MacOS
* **Color scheme**: One Dark
* **MagicPython version**: 1.0.12
* **A sreenshot**:  ![sc](https://snag.gy/rp4OGF.jpg)
* **5-10 lines of surrounding code**:

```
sequence = sequence.upper()
    
# calculate the GC content
GC_content = (sequence.count("G") + sequence.count("C")) / len(sequence)
```

Note that GC_content is a variable, not a constant in this case and therefore shouldn't be highlighted as such.

**Comment by 1st1** [comment]
See this issue where we elaborate on the current design. https://github.com/MagicStack/MagicPython/issues/42
