### ISSUE TITLE
Grammar hangs

### ISSUE THREAD

**Issue by aeschli** [MagicStack/MagicPython#150]
From https://github.com/Microsoft/vscode/issues/56377

Freezes have been reported with the following sample codes:
```
cmd = "git-clang-format --style=\"{{BasedOnStyle: Google, ColumnLimit: 100, IndentWidth: 2, " \ "AlignConsecutiveAssignments: true}}\" {COMMIT_SHA} -- ./**/*.proto > {OUTPUT}".format(
```

```
record = {
    "headers": {k: str(v) for k, v in self.request.META.items() if k.startswith('HTTP_')}
}
```

**Comment by elprans** [comment]
I can reproduce in 1.27.2. @vpetrovykh fb56c6a98d684e30bed1b0f9647e85741a48f914 is breaking this. Please take a look.

**Comment by 1st1** [comment]
We'll make a release with the bug fix shortly.
