### ISSUE TITLE
Python string like r'.\xxx.jpg' causes editor rendering error color.

### ISSUE THREAD

**Issue by aeschli** [MagicStack/MagicPython#152]
_From @thesby on August 15, 2018 10:13_

```python
path = r'.\023455.jpg'
```

input the code into your editor, you will find that the color '023' is error, seeming that no 'r'.

**Comment by 1st1** [comment]
Raw strings (`r""` and `r''`) are highlighted as regexps in MagicPython. There's no bug here, just the intended behavior.

**Comment by aeschli** [comment]
@thesby FYI, maybe describe better what the bug is.

**Comment by 1st1** [comment]
I guess it was highlighted with red color or something, depending on the color scheme. But again, this is expected behavior.
