### ISSUE TITLE
Cannot style a python module a different color than a python variable

### ISSUE THREAD

**Issue by codeliger** [MagicStack/MagicPython#153]
https://github.com/Microsoft/vscode-python/issues/2409

## Environment data

- VS Code version: 1.26.1
- Extension version (available under the Extensions sidebar): 2018.7.1
- OS and version: Windows 10 Education Version 10.0.17134 Build 17134
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): None

## Actual behavior

Python modules are identified as `source.python` when using **Inspect TM Scopes**

## Expected  behavior

Python modules have a unique identifier allowing for different stylization settings than standard python variables when using *Inspect TM Scopes*

## Steps to reproduce:
1. Create a blank python file
2. Import a module
3. Access *Inspect TM Scopes* from the 'Command Pallete'
4. Click on the module name you imported
5. Observe no unique identifier assigned from the language parser

![django](https://user-images.githubusercontent.com/9361348/44285720-76cdd480-a234-11e8-9646-2b129d5b07e2.jpg)

**Comment by 1st1** [comment]
This is a neat idea but it's beyond of what editors allow syntax highlighters to implement consistently.  We could only highlight module names in `import` statements, but not in other code.  Thank you for the suggestion though.
