### ISSUE TITLE
Python highlighting - raw string literals incorrectly colour escape sequences in some cases

### ISSUE THREAD

**Issue by aeschli** [MagicStack/MagicPython#155]
_From @akdor1154 on August 30, 2018 0:54_

 

- VSCode Insiders Version: 1.27.0-insider 47d0584301d16d4efd6618f6f33ef14099c92561 x64
- VSCode Stable Version: 1.26

- OS Version: ubuntu 18.04 x64

Steps to Reproduce:

1. Open/create a python file
2. Write a raw string with some backslashes as a function parameter:
```py
open(r'C:\Jenkins\new-file.xml')
```
Observe the backslashes are incorrectly shown as being part of an escape sequence. Raw strings literals have literal backslashes, you can't write escape sequences in them. The string should be a solid colour. `\n` should not be highlighted as it is in a raw string, and `\J` should not be highlighted as it's not even an escape sequence in a normal string (normal string highlighting behaves correctly here).
Looks like GitHub highlighting gets it wrong too. :)

![image](https://user-images.githubusercontent.com/6732831/44823302-06b34b80-ac43-11e8-8d28-0b46db8c43a1.png)

_Copied from original issue: Microsoft/vscode#57555_

**Comment by 1st1** [comment]
We highlight raw strings with Regexp syntax, that's what original users of tmLanguage schemas in TextMate and SublimeText expected. We can probably compile a special version of MagicPython that wouldn't have this feature, but then you'll get a lot of negative feedback that we broke this feature in VSCode.  So as is, this isn't a bug in current MagicPython, it's a feature.

**Comment by UncleGoogle** [comment]
VSCode user here. Please reopen this issue. r'strings' are `string literals`, not the `regex literals`! It can be used for example for windows filesystem paths without manually changing every slash to double slash...

I know that it is used often in regex. But this feature should be handle differently. At least provide some config, to set it manually.

Snippet below doesn't looks like a feature at all. 

![1ccc3b6b8d95c07eda9806d4b0831b7c](https://user-images.githubusercontent.com/12197825/62124101-aa7cff80-b2c9-11e9-8e41-f648bd7e84a6.png)
