### ISSUE TITLE
Build system is not working

### ISSUE THREAD

**Issue by yichuan1118** [MagicStack/MagicPython#16]
Hi I used to be able to use ctrl+B to run python scripts in sublime. After switching to MagicPython, it is not working.

**Comment by yichuan1118** [comment]
It seems I have to re-enable 'python' package in sublime to make ctrl-b works again.

**Comment by 1st1** [comment]
Thanks for reporting! Fixed in v0.4.30 -- should hit Package Control update channel soon.
