### ISSUE TITLE
Updating to “MagicPython@1.1.0” failed

### ISSUE THREAD

**Issue by bigheadming** [MagicStack/MagicPython#164]
* **Editor name and version**: Atom 1.31.1 x64
* **Platform**: Windows 10
* **Color scheme**:  UI Theme: Seti, Syntax Theme: Atom Dark
* **MagicPython version**: 1.0.12
* **A sreenshot**: 
![image](https://user-images.githubusercontent.com/31396275/46514400-6349ed80-c823-11e8-9e44-ca46b4eacb7a.png)

* **5-10 lines of surrounding code**: error code appeared in debug.log:
2075 verbose argv "C:\\Users\\xxx\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\xxx\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\xxx\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\xxx\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/magicpython/versions/1.1.0/tarball" "--runtime=electron" "--target=2.0.7" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style"
2076 verbose node v8.9.3
2077 verbose npm  v6.2.0
2078 error code ELIFECYCLE
2079 error errno 1
2080 error oniguruma@7.0.2 install: `node-gyp rebuild`
2080 error Exit status 1
2081 error Failed at the oniguruma@7.0.2 install script.
2081 error This is probably not a problem with npm. There is likely additional logging output above.
2082 verbose exit [ 1, true ]

**Comment by kylebarron** [comment]
Install also failed for me.

It seems that oniguruma is a new dependency as of 1.10: https://github.com/MagicStack/MagicPython/commit/f340032d0ed35f0b94323537f95cb256ea82ebb5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2.

node-gyp needs Python 2 and Atom has difficulties providing npm with the right Python version: https://github.com/atom/apm/issues/698.

I'm not sure why Atom is installing oniguruma if it's a devDependency though.

**Comment by kylebarron** [comment]
Thanks. It worked for me.

**Comment by 1st1** [comment]
Great! Closing the issue then, thanks for reporting!
