### ISSUE TITLE
Question: Highlights error with type? 

### ISSUE THREAD

**Issue by romelgomez** [MagicStack/MagicPython#168]
This issue was resolved? https://github.com/Microsoft/vscode-python/issues/859  They are referring to this repo. 

I just copy paste the function section and I'm getting inconsistencies:
https://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html#functions

![screenshot from 2018-10-30 12-14-50](https://user-images.githubusercontent.com/2358251/47736834-88245b80-dc3d-11e8-8a77-fc8dbf20bbcc.png)

* **Editor name and version**: 
Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
* **Platform**: Ubuntu 18.04.1 LTS 
* **Color scheme**: Default
* **MagicPython version**: 1.1.0
* **A sreenshot**:

* **5-10 lines of surrounding code**:

**Comment by elprans** [comment]
You have an extension that conflicts with MagicPython.  Most likely it's "Python for VSCode".  See also #162.
