### ISSUE TITLE
Scope triple single and triple double slightly different

### ISSUE THREAD

**Issue by facelessuser** [MagicStack/MagicPython#17]
According to PEP257 triple double quotes should be used as docstrings.  Now I realize that not everyone may buy into this, but I generally use the triple double for my docstrings and triple single for regex etc.  Then I usually style my docstrings as comments in my color scheme.  It would be nice if MagicPython at least scoped triple single and triple double slightly different.  Simply adding in a "single" or "double" specifier would be more than sufficient.

**Comment by 1st1** [comment]
Docstrings have one of the following scopes:

    string.quoted.docstring.multi.python
    string.quoted.docstring.python
    string.quoted.docstring.raw.multi.python
    string.quoted.docstring.raw.python

Other strings have this ones:

    string.quoted.binary.multi.python
    string.quoted.binary.single.python
    string.quoted.multi.python
    string.quoted.raw.binary.multi.python
    string.quoted.raw.binary.single.python
    string.quoted.raw.multi.python
    string.quoted.raw.single.python
    string.quoted.single.python

And here are the scopes for regexps:

    string.regexp.quoted.multi.python
    string.regexp.quoted.python

If you have a string as part of an expression if will be scoped as a string or as a regex string.  If it's a statement -- it will be scoped as a docstring.  Please check if this is enough for you to style.

Introducing `double`/`single` subscopes is doable, but will require us to duplicate many rules for docstrings (at least), which I'd want to avoid.

**Comment by facelessuser** [comment]
> If you have a string as part of an expression if will be scoped as a string or as a regex string.

Nice, this is probably all I need then.  I have only briefly explored the scopes and incorrectly assumed that *all* triple quotes were styled the same.  But as only standalone string blocks are scoped as docstrings, I shouldn't ever have a conflict.

**Comment by 1st1** [comment]
Alright!  BTW, all the scopes that MP uses are listed here: [misc/scopes](misc/scopes) (the list is autogenerated).

**Comment by facelessuser** [comment]
Thanks!  It's nice to see a fresh take on Python syntax highlighting.  I always considered starting one from scratch...but laziness kept getting in the way :smile:.

**Comment by 1st1** [comment]
> Thanks! It's nice to see a fresh take on Python syntax highlighting. I always considered starting one from scratch...but laziness kept getting in the way :smile:.

Thanks :) I really hope that with MP we've covered all use cases and people's needs.

**Comment by 1st1** [comment]
FWIW I've just updated scopes for single line regexps and docstrings to be more consistent with scopes for regular strings (in e26b18dafd78f27e3918b08f9acfc67e0a2e0d9d and 92bed5a33d79873e5bb726f9aae41d223599c92b).  Closing this issue.
