### ISSUE TITLE
Missing highlightning for multi-line comments

### ISSUE THREAD

**Issue by niklasengvall** [MagicStack/MagicPython#170]
* **VS Code 1.30.1**:
* **Linux Mint 19**:
* **Dark+**:
* **MagicPython 1.1**:

When I try to multi-line comment there is no highlightning!

'''
print("""These lines is not executed, because they are inside of 3 beginning apostrophes an
and 3 ending ones as well""")
'''
It would be nice if highlightning could be included for this function, even if the big masses don't use triple apostrophes. Despite of that the creators of Python have implemented support for multi-line comments. 

Thanks in forward.
Niklas Engvall

**Comment by 1st1** [comment]
Multi-line string literals and docstrings are fully supported by MagicPython from day 1. There must be a configuration error in your editor. One of the known problems is using MagicPython with the  'Python'  extension.
