### ISSUE TITLE
UTF-8 Strings are not always handled correctly.

### ISSUE THREAD

**Issue by rk-h** [MagicStack/MagicPython#171]
* **Editor name and version**: Visual Studio Code Version 1.30.1 (1.30.1)
* **Platform**: Mac OS
* **Color scheme**: One Dark Pro Vivid
* **MagicPython version**:1.1.0

I asked on Stackoverflow for help with a UTF-8 Problem. This is the link: https://stackoverflow.com/questions/54052140/how-to-handle-a-utf-8-string-for-the-printing-and-the-storage-into-a-file-simult  

As it turned out, the error occurs only within VS Code. When I start the script from a terminal, it runs without errors. 

This is the script that does not run from within VS Code and MagicPython:
`
rootdir = u'/Users/x/y/z/'
with open('temp.txt', 'w', encoding='utf8') as logfile:
    for subdir, dirs, files in os.walk(rootdir):
        for file in files:
            file = os.path.join(subdir, file)
            print(file)
            logfile.write('Reading file: "' + file + '"\n')
            size = os.path.getsize(file)
            print(size)
`

And this is one of the filenames that caused trrouble: `"/Users/x/y/z/herbert_grönemeyer_concert.mp4"`

Edit: typo

**Comment by elprans** [comment]
I don't think this is the right place to report this.  MagicPython only does syntax highlighting and nothing else.  Please open an issue over at https://github.com/Microsoft/vscode-python.
