### ISSUE TITLE
How to customize variable name colors

### ISSUE THREAD

**Issue by Glaxy-Auditore** [MagicStack/MagicPython#173]
* **Editor name and version**: Visual Studio Code 1.30.2
* **Platform**: Windows10 1809
* **Color scheme**: Dark+(default)
* **MagicPython version**: 1.1.0

```python
dogs = []
hero = 'abc'
grone = 123
```
How to modify the colors of "dogs", "hero", "grone" in the above code?
Which scope in misc/scopes corresponds to this change?
I've tried all the scopes that contain "variables".

```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "scope": 
            "settings": {
                "foreground":"#DCDCAA"
            }
        }
    ]
}
```

**Comment by elprans** [comment]
You can inspect the scope by putting the cursor in the relevant place and running the "Inspect TM Scopes" command:

![screenshot_20190204_115505](https://user-images.githubusercontent.com/347119/52223630-09f6d700-2874-11e9-8f92-3f752bc542b9.png)

**Comment by elprans** [comment]
Also: https://code.visualstudio.com/blogs/2017/02/08/syntax-highlighting-optimizations
