### ISSUE TITLE
Issue with select-larger-syntax-node keybinding issue

### ISSUE THREAD

**Issue by lucasczpnk** [MagicStack/MagicPython#177]
## env details:
* **Editor name and version**: Atom 1.35.0
* **Platform**: Linux Ubuntu 18.04.2 LTS
* **Color scheme**: zacks-rainglow-syntax
* **MagicPython version**: 1.1.1
* **A sreenshot**: ![issue-screenshot](https://i.imgur.com/76rtV8I.png)
* **5-10 lines of surrounding code**: It happens on any python file, even with this shitty example
``` python
def test(**args):
    var = None
    var = str(var)
    print(var)
    return var

test()
```

As reported on this Atom discussion [post](https://discuss.atom.io/t/magicpython-issue-select-larger-syntax-node-keybinding-issue/63617), the select-larger/smaller-syntax-node keybinding command is not being executed when prompted.

I've tried a few different things like creating an equivalent custom bind in the keymap.cson file (with both the same keymap and with a couple different hotkey combinations), switching the grammar in the file to other languages, but none worked properly.  

Last night I had noticed that the core python syntax package was disabled, and after re-enabling said package the keybinding started working again. Today after a fresh boot, the issue was happening again.

I've tried disabling/enabling the core python syntax, same as last night, but to no avail. But as I was testing, when I switch the file grammar from MagicPython to the core python the keybinding works properly.

**Comment by DamnedScholar** [comment]
This is not a bug with MagicPython. The syntax node commands only work with Tree-sitter grammars, which MagicPython is not.

**Comment by lucasczpnk** [comment]
Had to desist on Maic Python :cry:
