### ISSUE TITLE
Incorrect syntax highlighting for rf strings

### ISSUE THREAD

**Issue by janosh** [MagicStack/MagicPython#186]
## Environment data

- VS Code version: 1.36.0
- MagicPython version: 1.1.1
- OS: macOS 10.14.5
- Color scheme: Dark+ (default dark)
- Python version: 3.6.7 (miniconda)

## Expected behavior

Combining raw strings and f-strings, I'd expect syntax highlighting inside curly brackets.

![f-string](https://user-images.githubusercontent.com/30958850/61174395-3fc48800-a597-11e9-91e4-a0151cc92b01.png)

## Actual behavior

But what I get is the uniform dark red color of raw strings.

![rf-string](https://user-images.githubusercontent.com/30958850/61174405-68e51880-a597-11e9-9553-a48db39ba694.png)

## Related

Issue was originally raised in https://github.com/microsoft/vscode-python/issues/6572.

**Comment by lmcarreiro** [comment]
Another related problem: https://github.com/Microsoft/vscode-python/issues/2445

![image](https://user-images.githubusercontent.com/13019179/67416179-bf9dbd80-f59c-11e9-9cac-121f9a3d99f8.png)

**Comment by vors** [comment]
This is a bad idea, please consider dropping it.

**Comment by kelvinwop** [comment]
![image](https://user-images.githubusercontent.com/30770221/72953180-d9949b00-3d59-11ea-90e9-a33554cc30e2.png)

capital R makes it do the fstring highlighting

**Comment by janosh** [comment]
@vpetrovykh Thanks for this advice. Unfortunately, it's not currently usable with `black` formatting since `black` automatically lower cases r-string prefixes. I opened [black#1244](https://github.com/psf/black/issues/1244) to discuss this.

**Comment by elprans** [comment]
@janosh Use `--skip-string-normalization` for black to disable the lowercasing behavior.

**Comment by janosh** [comment]
@elprans IIUC, this has other effects besides preventing r-string prefixes from being lower cased (such as not converting single to double quotes).

Btw, just tested it and it works with auto-format on save by adding `skip-string-normalization = true` under `[tool.black]` to `pyproject.toml`.

**Comment by gazzar** [comment]
I think this decision by the MagicPython devs to apply additional special meaning to a part of the Python language definition is a mistake. I've been wondering for a while why all my raw strings (which are almost never regex's) are highlighted weirdly by VSCode. It's nice to finally understand what's going on but it imposes mysterious behaviour on downstream projects. The simple question is, can this behaviour be disabled by downstream projects by some configuration option?

**Comment by MichaelBrown08** [comment]
I have struggled with this issue constantly. Sometimes disable -> enable works and gets the f-strings highlighting back, but when using WSL this is no longer possible. With MagicPython installed I still don't have f-string highlighting:

![image](https://user-images.githubusercontent.com/46346590/73662414-a7593680-4693-11ea-951d-d384c015f0a7.png)

How do I consistently, without needing to install and reinstall, get the f-string highlight?

**Comment by 1st1** [comment]
> I think this decision by the MagicPython devs to apply additional special meaning to a part of the Python language definition is a mistake. 

FWIW I agree, that probably was my mistake. The problem is that reverting this isn't an option now -- as magicpython is used by GH to highlight Python code and by multiple IDEs. Millions of people use it daily. To be fair, millions of people used TextMate & SublimeText before that also highlighted `r'strings'` as regexps.

@vpetrovykh @elprans That said I think that `fr'strings'` shouldn't be highlighted as regexps, so perhaps we should revert that change.

> I have struggled with this issue constantly. Sometimes disable -> enable works and gets the f-strings highlighting back, but when using WSL this is no longer possible. With MagicPython installed I still don't have f-string highlighting:

That seems like a not relevant issue. Perhaps your editor has some plugin that interferes with MagicPython.

**Comment by vpetrovykh** [comment]
Yes, looks like f-strings should be format strings first and foremost, regardless of what other flavor they have.

**Comment by elprans** [comment]
+1 for handling `fr'foo'` as f-strings.  As for the r-strings, we can probably ship an alternative grammar file and have downstream make their choice.

**Comment by gazzar** [comment]
> > I think this decision by the MagicPython devs to apply additional special meaning to a part of the Python language definition is a mistake.
> 
> FWIW I agree, that probably was my mistake. The problem is that reverting this isn't an option now -- as magicpython is used by GH to highlight Python code and by multiple IDEs. Millions of people use it daily. To be fair, millions of people used TextMate & SublimeText before that also highlighted `r'strings'` as regexps.

I think that, at least in the case of VSCODE, they might be happy if this behaviour was reverted. I'm not sure about GH or the other IDE devs' opinions; you would know better than me. Would it be possible to overload the parser to provide an alternative API that the IDEs could swap to or expose to their end users to select whether to use the regex-highlighted version or a plain-string version?

**Comment by adamkeinan** [comment]
I've had the same problem lately. Drove me crazy. 
1.checked all my setting to verify there's no overlap
2.check the extensions folder to verify i don't have inconsistent versions
3.simply re-selected my Interperter+path, and that did the job

**Comment by justanotheranonymoususer** [comment]
> capital R makes it do the fstring highlighting

Stumbled upon this today, too. Doesn't make sense and confusing. Would be great to get this fixed.

**Comment by silkfire** [comment]
Why hasn't this been fixed yet? Shouldn't be that hard to add `r` to the same highlighting category as `r`.

**Comment by brownjoel** [comment]
Is it possible to have `rf""` strings support both highlighting styles?  If I construct a regex as simply `r""`, it works beautifully:
![image](https://user-images.githubusercontent.com/34556033/221411332-65bf8744-1cc6-4088-a19e-9a72911e6896.png)

but if I use a format string to help clarify the regex logic, I lose the extremely helpful color variation of the special characters:
![image](https://user-images.githubusercontent.com/34556033/221411344-e4f7a284-d486-4d15-9bca-64b766c8380e.png)

While I'm very glad that the f strings are coming in correctly now, I do miss the rest of the `r` highlighting.
