### ISSUE TITLE
unwrapping function parameters

### ISSUE THREAD

**Issue by iulianbute** [MagicStack/MagicPython#187]
Issue Type: <b>Bug</b>

function declaration like:
def funcName ( ( xx , yy ) , zz = 'ABC' )
results in marking as unknown variables xx , yy.
code works fine but there are warnings.

Extension version: 1.1.0
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.74GB free)|
|Process Argv|cleanset_filter.py|
|Screen Reader|no|
|VM|67%|
</details>

**Comment by 1st1** [comment]
MagicPython only highlights your code. It doesn't generate warnings.
