### ISSUE TITLE
'in' in the control flow 'for ... in ...' syntax is sometimes recognized as a logical operator

### ISSUE THREAD

**Issue by alexr00** [MagicStack/MagicPython#193]
From @tweakimp in https://github.com/microsoft/vscode/issues/85271

- VSCode Version: 1.40.1 and 1.41.0-insider
- OS Version: Win 10 64bit

Steps to Reproduce:
Type in this python code and use `Developer: Inspect TM Scopes` to look at the `in` keyword in each line.
```python
x = [y + 3 for y in range(3)]  # 'in' is recognized as logical operator, but is part of the control flow
z = any(y == 3 for y in range(7))  # 'in' is rightfully recognized as control flow operator

for a in x:  # 'in' is recognized as logical operator, but is part of the control flow
    if a in x:  # 'in' is rightfully recognized as logical operator
        pass
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by vpetrovykh** [comment]
The short answer is that telling the difference between `in` as a logical operator and control flow is non-trivial, because very complex expression-looking things can follow `for`. E.g. `for x, [a, (b, c)] in func(z)`. So overall the detection is unreliable.

I have an idea that I can try to increase this reliability a bit for more cases.

**Comment by tweakimp** [comment]
I noticed more inconsistencies:
```python
a = any([x in [] for x in [1,2,3] if x in [2,3,4]])
b = any(x in [] for x in [1,2,3] if x in [2,3,4])
```
In the first line, every `in` is evaluated as a logical operator, although the middle one is a control flow operator.
In the second line, every `in`  is evalutated as a control flow operator, although the first and last are logical operators.

@vpetrovykh What do you think about the following rule:
`in` is always a logical operator, but a `for` turns the next `in` into a control flow operator.
Would that work? Is there any way to have a correct syntax in which this rule is not correct?

**Comment by tweakimp** [comment]
@vpetrovykh any update on this?
