### ISSUE TITLE
# in raw triple quote string

### ISSUE THREAD

**Issue by verhovsky** [MagicStack/MagicPython#194]
https://github.com/python/cpython/blob/be287c319124b7eb59ef32b69cf837ae3e99acab/Lib/string.py#L31

this line

```python
punctuation = r"""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""
```

has a `#` symbol in a `r"""` string, and the rest of the characters are highlighted as if it's a comment.

**Comment by verhovsky** [comment]
Looks like this is related to https://github.com/MagicStack/MagicPython/issues/114#issuecomment-349115524_

```python
punctuation = R"""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""
```

Please consider dropping this feature no one knows about.

**Comment by elprans** [comment]
This doesn't seem right even in regex mode.  The syntax for regexp comments is `(?#...)`, `#` on its own is not sufficient.

**Comment by 1st1** [comment]
# on its own is a comment. Check it.

**Comment by 1st1** [comment]
At least with re.X

**Comment by elprans** [comment]
Yes, you're right.
