### ISSUE TITLE
TODO in comment does not correctly highlighted

### ISSUE THREAD

**Issue by 358319765** [MagicStack/MagicPython#199]
* **Editor name and version**:
- Editor: VSCode
- version:1.42.1
* **Platform**:
- Windows 10
* **Color scheme**:
- comment
* **MagicPython version**:
1.1.0
* **A sreenshot**:
![屏幕截图(20)](https://user-images.githubusercontent.com/44105716/75207846-db1c0d80-57b4-11ea-9509-8f57184f3749.png)

* **5-10 lines of surrounding code**:
```python
def foo(a, b):
    # TODO
    # add a and b
    return a + b
```
I don't know if the highlight of `TODO` in comment should be differ from others or not, but what should i do if i want to make it same with others? do i need to configure somethind?

**Comment by 358319765** [comment]
![屏幕截图(20)](https://user-images.githubusercontent.com/44105716/75208111-9b095a80-57b5-11ea-89a8-0e73fe08a4b4.png)
This is the screenshot since above could not correctly show.

**Comment by 358319765** [comment]
It's weired that I once saw `TODO` in snippet above was same with other comment, but now `TODO` is different again. so weired huh.

**Comment by 1st1** [comment]
It's a feature to make TODO and XXX comments more prominent.
