### ISSUE TITLE
Highlight function names in function calls

### ISSUE THREAD

**Issue by 0942v8653** [MagicStack/MagicPython#2]
[PythonImproved](https://github.com/MattDMo/PythonImproved) allows for highlighting of the function name (the word just before the open parenthesis in a function call, not including `.`). See lines 9 and 23 in the screenshot below.

![PythonImproved screenshot](https://cloud.githubusercontent.com/assets/8689794/10593976/484d3fc8-7696-11e5-8538-161e945a8488.png)

The relevant tmLanguage syntax is [here](https://github.com/MattDMo/PythonImproved/blob/b148a9185f0f80b1cdef1330b0da063016024a78/PythonImproved.tmLanguage#L447-L461).

**Comment by 1st1** [comment]
Implemented in 489a57e0ea8f582db4da78d4de7635b8f73a5124. Will be released soon. Thanks!

**Comment by 1st1** [comment]
released in v0.4.21.

**Comment by s-trooper** [comment]
in v0.5.7 ether with default themes nor Chromodynamics the functions names are Highlighted!
