### ISSUE TITLE
positional argument specifier in string is not highlighted in Atom

### ISSUE THREAD

**Issue by austincrft** [MagicStack/MagicPython#20]
Default Python syntax:
![image](https://cloud.githubusercontent.com/assets/3616544/10709188/8fea4632-79e8-11e5-9008-784870610f0e.png)

MagicPython syntax:
![image](https://cloud.githubusercontent.com/assets/3616544/10709190/a897a846-79e8-11e5-8bbd-5556fbf87d99.png)

**Comment by 1st1** [comment]
Should be fixed in v0.4.34. Please update.

(See for details 9f7e839aca1e067691df2aef42572be636642f69 and d78bdaa88d00cd3a0c387722edc5062a604c6dda)

**Comment by austincrft** [comment]
Works perfectly, thanks!
