### ISSUE TITLE
support for snakemake

### ISSUE THREAD

**Issue by goi42** [MagicStack/MagicPython#202]
Right now, `MagicPython` only has automatic syntax highlighting for files called `Snakefile`. It would be nice if `.smk` files were also supported, as they are for [`language-python`](https://github.com/atom/language-python/blob/ad49f4a498987056b0f4fe5bbdf02dc685dde5cd/grammars/python.cson#L16-L17). 

It's getting tiresome constantly changing the highlighting manually...

**Comment by 1st1** [comment]
Please make a PR!

**Comment by goi42** [comment]
Done in #203 . Waiting for merge.
