### ISSUE TITLE
Item access not only with variables

### ISSUE THREAD

**Issue by echasnovski** [MagicStack/MagicPython#205]
Using item access with anything other than a variable isn't recognized as item access.

I have set "punctuation.definition.arguments" to a custom color in order to highlight brackets and parenthesis only if they are used for item access and function call respectively. However, it doesn't work in all cases when item access is actually done.

* **Editor name and version**: VS Code 1.44.1
* **Platform**: Ubuntu 18.04
* **Color scheme**: Customized "Solarized Dark" (color of "punctuation.definition.arguments" is set to "#b58900")
* **MagicPython version**: the one shipped with VS Code
* **A sreenshot**:
![magicpython_item-access](https://user-images.githubusercontent.com/24854248/79648436-336dfb00-81b9-11ea-815e-d8d6335d1029.png)
Expectation here is that all cases of `[0]` should have colored brackets.
* **5-10 lines of surrounding code**:
```python
x = [1, 2, 3]
x[0]
sorted(x, reverse=True)[0]
(x)[0]
(sorted(x))[0]
("a", "b")[0]
["a", "b"][0]
{0: "a", 1: "b"}[0]
```

I can see that solving this might be tricky, but highly appreciated.

**Afterthought**: Seems like detecting item accessing can be done by the rule "if `[`'s first preceding non-blank character is present and is not [operator](https://docs.python.org/3/reference/lexical_analysis.html#operators)". All other cases of `[` is a list creation. However, capturing object which items are accessed is challenging with regular expressions.

**Comment by vpetrovykh** [comment]
I can use a trick similar to the one for detecting function calls and kwargs when they aren't preceded by a plain function name. So I should be able to distinguish the array literals from item access that way  in most cases.
