### ISSUE TITLE
Multiline comment beginning with r""" and char "[" inside breaks highlighting

### ISSUE THREAD

**Issue by rmsilva1973** [MagicStack/MagicPython#206]
* **Editor name and version**: Visual Studio Code 1.44.2
* **Platform**: Windows 10
* **Color scheme**: High Contrast
* **MagicPython version**: Embedded in VS Code
* **A sreenshot**:
![image](https://user-images.githubusercontent.com/28487379/79688905-d4939a80-8227-11ea-9b20-3ee1ac677c73.png)

* **5-10 lines of surrounding code**:
r"""[
"""

print('Hello bug')

**Comment by elprans** [comment]
I cannot reproduce:

![image](https://user-images.githubusercontent.com/347119/80845968-b3379480-8bbf-11ea-982f-d4f56fcd1701.png)

Are you sure you're not using any extension that might have overridden the syntax highlight for Python, like "Python for VSCode" (not to be confused with the official Python extension from Microsoft)?

**Comment by rmsilva1973** [comment]
@elprans That was it. Sorry for the bogus bug report. :-)
