### ISSUE TITLE
Functions with annotations for return type are not showing consistently

### ISSUE THREAD

**Issue by cbnfreitas** [MagicStack/MagicPython#213]
Hi MagicPython guys! 

* **Update**: Please ignore this issue. It was a conflict with another extension: [Python for VSCode ](https://marketplace.visualstudio.com/items?itemName=tht13.python)

*  **Description** I'm facing an issue with syntax highlighting in MagicPython. Most specifically, in regard to annotations for return type: "if" and "return" are shown with the wrong colors (see some_fun_b below).  Kindly consider to check it and/or tell me if there's something wrong with my understanding.

* **Editor name and version**: VSCode
* **Platform**: Windows 
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

* **Color scheme**: Dark
* **MagicPython version**: 1.1.0 (the same occurs with both versions: the default one from VSCode Python Extension and MagicPython cutting edge).
* **A screenshot**:

![image](https://user-images.githubusercontent.com/25197031/83328752-c6d82880-a25b-11ea-887f-3a1b0f6671b2.png)

* **5-10 lines of surrounding code**:

def some_fun_a(x: int):
  if x==4:
    return True
  elif
    return False
    
def some_fun_b(x: int) -> bool:
  if x==4:
    return True
  elif
    return False

def some_fun_c(x: int):
  if x==4:
    return True
  elif
    return False

**Comment by danielbom** [comment]
It was solved?

**Comment by cbnfreitas** [comment]
Yes, it was a conflict with another VSCode Extension. Thanks for asking

**Comment by gaieges** [comment]
Thanks for updating that original ticket, that helped me too!

**Comment by etayluz** [comment]
For me it was this extension that was conflicting and I had to disable it to resolve this issue:
https://marketplace.visualstudio.com/items?itemName=tht13.python
