### ISSUE TITLE
Intellisense does not recognize new Pandas dataframe variable as such when it is assigned with Pandas concat function

### ISSUE THREAD

**Issue by Orionsg** [MagicStack/MagicPython#218]
* **Editor name and version**: VS Code 1.47.3 (system setup)
* **Platform**: Windows 10
* **Color scheme**: Dark+ (default dark)
* **MagicPython version**: 1.1.0
* **5-10 lines of surrounding code**:

```
import pandas as pd 

df_1 = pd.DataFrame()
df_2 = pd.DataFrame()
df_3 = pd.concat([df_1,  df_2])

df_3.rein
```
In the last line there are no suggestions for functions. Pressing ctrl+space just gives "No suggestions."

**Comment by 1st1** [comment]
MagicPython only does syntax highlighting.
