### ISSUE TITLE
Problems with the "from" keyword at the end of property names

### ISSUE THREAD

**Issue by tfeldmann** [MagicStack/MagicPython#22]
See screenshot (the from keyword should not be highlighted in purple):
![bildschirmfoto 2015-10-26 um 17 05 02](https://cloud.githubusercontent.com/assets/385566/10734515/f2ac9258-7c03-11e5-912e-40c3dc943a7e.png)

**Comment by 1st1** [comment]
Thanks for reporting this! Fixed in v0.4.36.

**Comment by tfeldmann** [comment]
Whew that was fast. Thanks for the great work!

**Comment by 1st1** [comment]
The power of unit tests! :)
