### ISSUE TITLE
How to use MagicPython? the color has not changed.

### ISSUE THREAD

**Issue by g2mXagent** [MagicStack/MagicPython#224]
* **Editor name and version**: Visual Studio Code 1.50.1
* **Platform**: Windows 10 x64
* **Color scheme**: Monokai (?)
* **MagicPython version**: 1.1.0
* **A sreenshot**: 
https://imgur.com/NRfTBHS
* **5-10 lines of surrounding code**: none

**Comment by elprans** [comment]
Visual Studio Code already includes MagicPython by default.  You should only install the extension if you want the latest fixes that have not yet been incorporated into VSCode.
