### ISSUE TITLE
python3: a # in an f-string breaks syntax highlighting

### ISSUE THREAD

**Issue by Spectre5** [MagicStack/MagicPython#225]
See the code below.  Since my issue exists on github, I can simply demonstrate my exact issue with the example code block below.  Basically, when a # is used within an f-string, then it appears to break the syntax highlighting.  It looks like the "#" in the f-string gets interpreted as the start of a comment, even though this is correctly handled for non-f-srings.  The # in the format string is used to get the alternate form for the hex conversion.  Here is an example of what the "#" does in a format string as well as demonstrate the bug:

```python
>>> # syntax highlighting works here...
>>> i = 5
>>> '{:#04x}'.format(i)   # <-- not using an f-string is fine
'0x05'
>>> f'{i:04x}'
'0005'
>>> f'{i:#04x}'           # <---- this line breaks the syntax highlighting
'0x05'
>>> f'{i:04x}'            # <-- syntax highlighting is broken!
'0x05'
>>> '{:#04x}'.format(i)   # <-- syntax highlighting is broken!
'0x05'
>>> 
```

Here is a screenshot to demonstrate the issue (for future reference) since, after this bug is fixed, the code above will presumably have the correct highlighting.

![Screenshot from 2020-11-11 17-49-24](https://user-images.githubusercontent.com/31610422/98885078-42aee180-2446-11eb-99f0-6e278192f777.png)

**Comment by elprans** [comment]
MagicPython highlights this snippet just fine:

![image](https://user-images.githubusercontent.com/347119/98887156-4c3a4880-244a-11eb-94d9-35b8ab7ef615.png)

The problem is that Github is now using something else for Python highlighting :-/  (I opened a PR to remove the outdated statement from the README).

**Comment by Spectre5** [comment]
ah, bummer.  I couldn't find anywhere to post an issue for github itself, so I thought I tracked down that this library is what they use, but apparently not!  Back to searching for what they use then...

**Comment by Spectre5** [comment]
Huh, do you have any idea what library they do use, then?  Per [this github documentation link](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-repository-languages), they use [linguist](https://github.com/github/linguist), but linguist indicates that they use MagicPython in their [grammar index](https://github.com/github/linguist/blob/master/vendor/README.md).

**Comment by Spectre5** [comment]
Could they just be using an old version, or are you sure they don't use MagicPython anymore?

**Comment by elprans** [comment]
Linguist is definitely using a fairly recent version of MagicPython.  You might try asking on the community forum at https://github.community/

**Comment by verhovsky** [comment]
For reference: https://github.community/t/what-library-does-github-use-for-python-syntax-highlighting/145558 

No one responded
