### ISSUE TITLE
In Atom, with MagicPython, linter-python can't highlight unnecessary imports

### ISSUE THREAD

**Issue by mythmon** [MagicStack/MagicPython#24]
Atom has a package, linter-flake8, that among other things will highlight unnecessary imports. With the standard Atom Python syntax highlighting, this works correctly. With the MagicPython syntax highlighting, the lint error always points at the end of the document.

**Comment by 1st1** [comment]
Could you please share some screenshots?

**Comment by mythmon** [comment]
With MagicPython:

![shot_9645](https://cloud.githubusercontent.com/assets/305049/11006930/719deb1e-847b-11e5-8eb2-3354a0223013.png)

With language-python:

![shot_10504](https://cloud.githubusercontent.com/assets/305049/11006945/936fa73c-847b-11e5-8492-ce871f9b948b.png)

**Comment by 1st1** [comment]
Should be fixed in `v0.4.43`

**Comment by 1st1** [comment]
This still has to be fixed. Working on that now.

**Comment by 1st1** [comment]
Now this should be fixed ;) Update to `v0.4.44`. Thanks for reporting this!

**Comment by mythmon** [comment]
Confirmed, this is working in v0.4.44. Thanks!

**Comment by carldunham** [comment]
Any chance this has regressed? I'm seeing this in Atom 1.6.1 with MagicPython 0.5.8 and linter-flake8 1.13.0

**Comment by 1st1** [comment]
I've just released `v0.5.9` where it should be fixed. Please try it.

**Comment by carldunham** [comment]
Wow, thanks for the quick response. That fixed it!
