### ISSUE TITLE
No ability to configure soft vs hard tabs when using tab type auto

### ISSUE THREAD

**Issue by agraubert** [MagicStack/MagicPython#248]
* **Editor name and version**: Atom 1.60.0 x64
* **Platform**: MacOS 11.6.4 (Big Sur)
* **Color scheme**: One Dark/Ariake Dark
* **MagicPython version**: 1.1.1
* **A sreenshot**:

Atom's Editor settings regarding tabs/spaces
![Screen Shot 2022-03-22 at 1 22 20 PM](https://user-images.githubusercontent.com/997749/159539080-54ae4f6e-a266-4050-95f6-fc3bd4f3e70c.png)
MagicPython's settings regarding tabs/spaces
![Screen Shot 2022-03-22 at 1 22 10 PM](https://user-images.githubusercontent.com/997749/159539082-4544163e-a9ba-4df1-afeb-e3330d28c0b8.png)
Video of observed tab behavior (indenting in a blank .py file inserts a soft tab)
https://user-images.githubusercontent.com/997749/159539085-5bf2d7d9-1e06-4ff7-91b6-30294a82ccf2.mov

--- 

I would expect MagicPython to either expose a `Soft Tabs` option or defer to the editor's `Soft Tabs` setting. Based on my current settings, MagicPython should attempt to infer tab type, but default to hard tabs (from editor settings) if auto-detection fails. Instead I observe MagicPython using soft tabs with no way to configure the fallback behavior. As I understand it, there does not seem to be a way to use hard tabs without setting the tab type to `Hard`

**Comment by hazarek** [comment]
This repo has been abandoned. It has been inactive for two years.

**Comment by agraubert** [comment]
Wow, I had not noticed. Thanks

**Comment by elprans** [comment]
> This repo has been abandoned. It has been inactive for two years.

Low-maintenance and "abandoned" are not the same, please don't speak for the maintainers.

@agraubert, regarding the original issue, MagicPython is just a syntax grammar for highlighting, I think Atom uses the grammar name in the settings title.  This is an Atom issue.

**Comment by agraubert** [comment]
If MagicPython is just syntax grammar, then why does it expose settings for indentation? I can assure you that MP settings for "how many spaces in a soft tab" (4 spaces) are overriding my core atom settings (2 spaces)

**Comment by hazarek** [comment]
> > This repo has been abandoned. It has been inactive for two years.
> 
> Low-maintenance and "abandoned" are not the same, please don't speak for the maintainers.
> 
> @agraubert, regarding the original issue, MagicPython is just a syntax grammar for highlighting, I think Atom uses the grammar name in the settings title. This is an Atom issue.

2 years means abandoned. don't fool yourself.

**Comment by agraubert** [comment]
I see. I did not realize that atom populates these settings for all grammars. Thanks for pointing me in the right direction
