### ISSUE TITLE
Python import aliases in uppercase are highlighted as constants

### ISSUE THREAD

**Issue by bofm** [MagicStack/MagicPython#29]
I have an import statement
```python
import xml.etree.ElementTree as ET
```
`ET` is highlighted as if it was defined as a constant like `ET = 1`.

Is it possible to fix this with the current capabilities of ST and it's syntax language?

**Comment by 1st1** [comment]
While it is possible to fix highlighting for that particular line of code, `ET` will still be highlighted as a constant in the rest of the code.  And that will be even more confusing :(
