### ISSUE TITLE
Tab size mangling

### ISSUE THREAD

**Issue by doerwalter** [MagicStack/MagicPython#31]
I've set my tab_size to 3 in `~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings`, however MagicPython seems to ignore that setting. Why is that, and how can I get my tab_size back?

**Comment by 1st1** [comment]
Can you try to do a per-language setting? Is it ST3?

**Comment by doerwalter** [comment]
Yes, it's ST3. Putting a `"tab_size": 3` into `~/Library/Application Support/Sublime Text 3/Packages/User/MagicPython.sublime-settings` works, but IMHO this shouldn't be neccessary.

**Comment by 1st1** [comment]
You should try to create a language-specific setting. I.e. it's possible to set different tab sizes per different languages in ST.  I'm not sure if it will work though.  In any case, I think it's a bug in ST -- MagicPython only wants to set a default tab size for Python files.

**Comment by doerwalter** [comment]
Setting the tab size in the language-specific settings file *does* work.

However this is not a bug in ST. The fact that MagicPython wants to set a tab size for Python files is the problem. IMHO it shouldn't.

**Comment by 1st1** [comment]
Alright, we'll consider removing this option in the next release. Closing this issue.

**Comment by mefryar** [comment]
My Default, User, and Syntax Specific settings (i.e. `~/Library/Application Support/Sublime Text 3/Packages/User/MagicPython.sublime-settings`) all have `"tab_size": 4` but MagicPython is still setting `"tab_size": 2`. Is there anything I might be doing wrong?

Sublime Text Version 3.1.1, Build 3176
MagicPython Version 1.1.1
