### ISSUE TITLE
Unicode character "ı" causes hangs 

### ISSUE THREAD

**Issue by altunyurt** [MagicStack/MagicPython#32]
I'm using 0.5.7 on dv 3099 build of sublime text. With this build, a string ending with mı, rı, ğı etc causes mp and eventually sublime text to become unresponsive. It does happen all the time with the given and a couple more similar strings but interestingly, not for all the strings that end in ı.

For example: strings ending with gı, nı, hı, şı etc do not cause any problems. With MP  disabled, sublime text does not hang or freeze.

**Comment by vpetrovykh** [comment]
This is a very interesting catch. We've previously experienced some issues with unicode that seemed to depend of the underlying system libraries. So this is something I'll try and check first for this use-case. In a way I hope that this is a more general failure that can be fixed generically, though.

**Comment by altunyurt** [comment]
Oh sorry, forgot to update here. I thought MP was the reason for the ST freeze, but after trying other highlighters, including the ST's default for python, it was clear that the problem was related with ST. Seems that the autocomplete+highlighting+unicode ends up freezing.

Some more details can be found at https://forum.sublimetext.com/t/3099-hangs-when-unicode-meets-syntax-coloring/16819

**Comment by 1st1** [comment]
Alright, I'm closing this.
