### ISSUE TITLE
Treat single-character capital names as class instead of constant

### ISSUE THREAD

**Issue by uranusjr** [MagicStack/MagicPython#34]
Currently, single-character words are highlighted like `ALL_CAPS_NAMES`, but in practice they are usually class names instead, such as [`Q`](https://docs.djangoproject.com/es/1.9/ref/models/querysets/#django.db.models.Q) and [`F`](https://docs.djangoproject.com/en/1.9/ref/models/expressions/#f-expressions) objects in Django.

It might be better to change the highlighting rule of constants to require at least two characters instead. (Or even two _uppercase_ characters because names like `_N` also look like a class. This might just be me though.)

**Comment by vpetrovykh** [comment]
Yeah, valid point. It really boils down to what is the more common use-case. However, we still plan on trying to make the highlighter more configurable and this may be a good configuration option to add. In the mean time I'll keep this thread open to let anyone else who might have an opinion on the matter chime in.

**Comment by 1st1** [comment]
Resolved as part of #42. Closing this issue now.
