### ISSUE TITLE
class keyword not highlighted in Visual Studio Code

### ISSUE THREAD

**Issue by erezak** [MagicStack/MagicPython#36]
class and some other keywords are not highlighted or colored differently.

Screenshot:
![magicpython](https://cloud.githubusercontent.com/assets/406695/13135212/4286d23a-d617-11e5-8a61-05cd2e7d315a.png)

**Comment by 1st1** [comment]
@erezak It's not really a bug of MagicPython -- it's a limitation of the `Dark` color scheme. I suggest you to try `Dark+` or `Monokai` (via Preferences/Color Theme).

**Comment by erezak** [comment]
You're completely correct :) Thank you.
