### ISSUE TITLE
Highlighting of pseudo-keyword "self"

### ISSUE THREAD

**Issue by personjerry** [MagicStack/MagicPython#4]
The convention of having methods refer to their calling instances by the parameter name "self" is so commonly accepted that "self" should probably highlighted.

**Comment by 1st1** [comment]
Implemented in e46428f9bd829a8f11867b448994f28745520689. Will be in the next release (soon).

New scopes are listed [here](https://github.com/MagicStack/MagicPython/commit/e46428f9bd829a8f11867b448994f28745520689#diff-e4925b9a8ec5667bfe531c6dc62d0b8a).

**Comment by 1st1** [comment]
released in v0.4.21. Thanks!
