### ISSUE TITLE
how to enable sublimeLinter with magicPython?

### ISSUE THREAD

**Issue by byaka** [MagicStack/MagicPython#40]
* **Editor name and version**: SublimeText 2
* **Platform**: Linux
* **Color scheme**: Dawn
* **MagicPython version**: latest stable
* **A sreenshot**: none
* **5-10 lines of surrounding code**: any

In sublimeText2 python files use 'MagicPython' (ofcourse if magicPython installed) as syntax scheme. But [sublimeLinter](https://github.com/SublimeLinter/SublimeLinter-for-ST2) wait for 'Python' syntax scheme. How to solve this?

**Comment by 1st1** [comment]
The latest SublimeLinter version should be pre-configured to support MagicPython.  Please try to update it.

**Comment by byaka** [comment]
Are you say about SublimeLinter for ST2 or for ST3?
I installed sublimelinter from scratch now, nothing happened.

**Comment by 1st1** [comment]
Right, I didn't know that sublimelinter for st2 is a different package. In this case, you probably need to add 

```json
{"MagicPython": "python"}
```

in `"sublimelinter_syntax_map"` setting or something like that. See also my PR https://github.com/SublimeLinter/SublimeLinter3/pull/352 to add MagicPython support in SL3.

Please report if this helped you.

**Comment by byaka** [comment]
my settings
```
    "sublimelinter_syntax_map":
    {
        "Python Django MagicPython": "python",
        "Ruby on Rails": "ruby",
        "C++": "c"
    },
```
it doesn't help

**Comment by 1st1** [comment]
Try

```json
    "sublimelinter_syntax_map":
    {
        "Python Django": "python",
        "MagicPython": "python",
        "Ruby on Rails": "ruby",
        "C++": "c"
    },
```

**Comment by byaka** [comment]
doesn't help too

**Comment by 1st1** [comment]
Well, in this case, I recommend you to reach out the guys who own SL.

**Comment by byaka** [comment]
thx, i will try

**Comment by 1st1** [comment]
And, last thing, try this:

```json
    "syntax_map":
    {
        "Python Django": "python",
        "MagicPython": "python",
        "Ruby on Rails": "ruby",
        "C++": "c"
    },
```

**Comment by byaka** [comment]
Oo it help! Thx you!

it so strange, "syntax_map" is variable for SublimeLinter3 and not documented in SublimeLinter2...
