### ISSUE TITLE
Built-in names in class scope should not be highlighted

### ISSUE THREAD

**Issue by uranusjr** [MagicStack/MagicPython#44]
Currently built-in names are highlighted in definitions, even when they are inside a class scope:

~~~python
class SomeClass:

    id = models.AutoField(...)   # Common in Django.

    def open(self):    # Also quite common. pathlib.Path.open is an example.
        pass

    class Exception:   # Less common, but possible.
        pass
~~~

I read the Built-ins and Magic Methods section in README, but am still not sure whether this is intentional. I can’t think of a case in which they can shadow built-in global names.

**Comment by 1st1** [comment]
You can actually have code in your class statements.  Let me show an example of shadowing the `sum` name in the class body:

```python
class Foo:
    spam = 'bar'
    sum = 123
    bar = 'spam'
  
    # Lot's of code before this line
    CONSTANT = sum([i for i in range(100)])

    # And now methods
    def say(self):
        return self.spam
```

Another thing is that I doubt we can detect that we're lexing a body of a class reliably. And even if that's possible, it would complicate the grammar too much.

So, unfortunately, this one is "won't fix".

**Comment by uranusjr** [comment]
Thanks for the explanation. Unfortunate indeed.
