### ISSUE TITLE
Support PyCharm

### ISSUE THREAD

**Issue by dufferzafar** [MagicStack/MagicPython#45]
Not a bug, but a feature request.

I use this on Sublime and it truly is magical, but I was wondering if this can somehow be integrated into PyCharm?

**Comment by 1st1** [comment]
Sorry for the late reply. I think that PyCharm has a way to import sublime text & textmate schemas, but I'm not sure how.  Is MagicPython better than what PyCharm provides out of the box?

**Comment by dufferzafar** [comment]
@1st1 I'm quite new to PyCharm, but as far as I can tell MagicPython has a lot of niceties that I couldn't find in PC.

**Comment by 1st1** [comment]
Closing this issue – this is something out of our control.
