### ISSUE TITLE
MagicPython doesn't work with VS Code under Windows 10

### ISSUE THREAD

**Issue by jakeargent** [MagicStack/MagicPython#46]
* **Editor name and version**: Visual Studio Code 1.2.1
* **Platform**: Windows 10
* **Color scheme**: Default
* **MagicPython version**: 0.5.11
* **A sreenshot**: 
![no magic](https://cloud.githubusercontent.com/assets/18471520/16356412/52043630-3adf-11e6-9463-a35250532915.jpg)

* **5-10 lines of surrounding code**:

I've had this issue for a while now, and it's slightly different in Windows 10 vs Linux Mint 17.3. In LM17.3 there's some coloring. For example `def func(arg1, arg2):` would have def as blue, func as yellow-ish, and the rest as white.

In any case, with Windows 10 the extension flat-out doesn't work as you can see in the screenshot.

**Comment by 1st1** [comment]
I'm not sure I see the problem -- everything is seems to be properly highlighted in the screenshot, albeit it seems that the linter is complaining about code style. Do you mean that MagicPython does not highlight function and coroutine names with a yellow color as the built-in VSCode Python highlighter does?

**Comment by jakeargent** [comment]
I've taken this screenshot with these lines as a comparison with the screenshot at the MagicPython github page. In that picture showcase is colored green, docstring and regular string are colored differently, and the parameter of the @decorator and it's assigned value are also colored, and different from each other.

Should I not expect these? If not, what should I expect with MagicPython?

P.S: I have MagicPython installed in both W10 and LM17.3 for VS Code. It behaves slightly differently between these OS's and its behavior doesn't match (or come close) to that of the screenshot present in the github page.

[This is the picture I'm talking about.](https://camo.githubusercontent.com/67d8c8fa28f03f13123e6d9a9b410e19a6c39f67/68747470733a2f2f6d61676963737461636b2e6769746875622e696f2f4d61676963507974686f6e2f6578616d706c652e706e67)

Linter's complaint is a red herring here.

**Comment by jakeargent** [comment]
That clears up some confusion and I'll close this issue.

How would I go about converting Chromodynamics to work with VS Code though? I've looked at alternatives and... they are better than default, but not that much.

**Comment by 1st1** [comment]
Please open an issue for VSCode compat for the Chromodynamics project. I'll try to take a look.

**Comment by scotthuang1989** [comment]
I can't install it on atom on windows 10. maybe it is the same issue?
