### ISSUE TITLE
No support for newline between function parameters and return type

### ISSUE THREAD

**Issue by alexjurkiewicz** [MagicStack/MagicPython#51]
* **Editor name and version**: Atom 1.9.3
* **MagicPython version**: MagicPython 0.5.13
* **A sreenshot**:
![screen shot 2016-08-09 at 2 22 16 pm](https://cloud.githubusercontent.com/assets/379509/17504505/b67a6db6-5e3c-11e6-9800-cc3ef4fbfc8c.png)

* **5-10 lines of surrounding code**:
```python3
@util.timer
def get_streaks(s: sqlalchemy.orm.session.Session,
                active: Optional[bool]=None,
                sort_by_length: Optional[bool] = False,
                limit: Optional[int]=None,
                ) \
        -> Sequence[Streak]:
```

Python runs this code just fine, it seems MagicPython doesn't handle newline continuations in this space properly. Removing the `\` has no effect on syntax highlighting.

**Comment by 1st1** [comment]
Should be fixed in `v0.5.14`.

**Comment by 1st1** [comment]
Thanks for reporting this!

**Comment by alexjurkiewicz** [comment]
Wow, thanks for the speedy fix!! Love this project :)

**Comment by 1st1** [comment]
Closing this issue. Please reopen if it's not resolved.
