### ISSUE TITLE
MagicPython overrides color scheme

### ISSUE THREAD

**Issue by apassy** [MagicStack/MagicPython#52]
ST3, 3114
win 10
customized Monokai
MP: 0.5.15

I'm trying to customize the display of classnames.  Here is the piece from my .tmTheme file:
```
 		<dict>
			<key>name</key>
			<string>Class name</string>
			<key>scope</key>
			<string>entity.name.class,  entity.name.type.class.python</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>underline  bold</string>
				<key>foreground</key>
				<string>#7D8BFA</string>
			</dict>

```
When I open the file, the class name is briefly styled like I want - then it's overridden, and changes to the default text color.

Class names work in Matlab and C++ files I work in.   I think this is a magicPython issue, but I'm not sure.

Any ideas?

**Comment by vpetrovykh** [comment]
MagicPython highlighter is not a color scheme. It does not actually set the _colors_ for anything. It sets scopes that tell the current color scheme how to apply colors. The change to the color scheme that you provided seems to work for me, but I am running a different ST3 build (3075) on linux.

I would suggest trying to break this rule into two, simply to check that it's not interpreted differently:
```xml
<dict>
    <key>name</key>
    <string>Class name</string>
    <key>scope</key>
    <string>entity.name.class</string>
    <key>settings</key>
    <dict>
        <key>fontStyle</key>
        <string>underline  bold</string>
        <key>foreground</key>
        <string>#7D8BFA</string>
    </dict>
</dict>

<dict>
    <key>name</key>
    <string>Class name</string>
    <key>scope</key>
    <string>entity.name.type.class.python</string>
    <key>settings</key>
    <dict>
        <key>fontStyle</key>
        <string>underline  bold</string>
        <key>foreground</key>
        <string>#7D8BFA</string>
    </dict>
</dict>
```

Overall this seems like an interaction with some other plugin that is causing the glitch for you. Do you have any plugins that could be affecting scopes? If you use a linter plugin, you may want to try disabling it to see if the interaction with it is affecting the colors. That may help narrowing down where the problem actually is.

**Comment by apassy** [comment]
How would I dump a list of plugins?  I have Anaconda, and SublimeLinter for other languages, at least for linters.

**Comment by 1st1** [comment]
MagicPython has nothing to do with color schemas, so I'm closing this issue. Please feel free to reopen if you can provide more details showing that it's really related to MP.
