### ISSUE TITLE
Curly braces inside string constants, shown in wrong colour

### ISSUE THREAD

**Issue by mattst** [MagicStack/MagicPython#54]
Curly braces inside string constants, are shown in the colour of the `constant` scope.

* **Editor name and version**: Sublime Text 3114
* **Platform**: Linux Mint 17
* **Color scheme**: My own based on `Boxy Tomorrow.tmTheme` but many colours altered, [see this Gist](https://gist.github.com/mattst/657f03d249090cfaf8665afedd3ef4d5).
* **MagicPython version**: 0.5.15

Screen capture with syntax set to MagicPython:

![st_magicpython_01](https://cloud.githubusercontent.com/assets/835623/18285595/0ab5ae6e-7467-11e6-80b1-e4a5ac08ffb2.png)

Screen capture with syntax set to PythonImproved (what I was using before MP):

![st_magicpython_02](https://cloud.githubusercontent.com/assets/835623/18285602/110f6912-7467-11e6-8316-90644f405179.png)

Hope this helps.

For your convenience the dictionary for the `constant` scope:

``` json
<dict>
    <key>name</key>
    <string>Constant</string>
    <key>scope</key>
    <string>constant, constant.language, support.constant, constant.character, constant.character.escape, constant.other, constant.other.color, constant.other.symbol, constant.other.key</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#EE1B2D</string>
        <!-- <string>#b5bd68</string> -->
    </dict>
</dict>
```

**Comment by 1st1** [comment]
This is actually a feature -- we highlight string formatting:

```python
print('{foo!r} {bar}', foo=42, bar='ham')
```

**Comment by mattst** [comment]
Okay, thanks. I thought it was a bug. Cheers.

**Comment by 1st1** [comment]
NP! ;)
