### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by rome702** [MagicStack/MagicPython#55]
I have installed the latest version of atom and magic python and following the instructions the text is not highlighting like it should. i attempted to use .format after a string and it still doesn't highlight.

**Comment by vpetrovykh** [comment]
Can you provide more details? What color scheme are you using? Can you share a code snippet that you think is not highlighted correctly?

Rule of thumb, though: strings don't care whether you write `.format` after or not. Instead we look at the contents of the string for either %-style formatting symbols or {}-style.

**Comment by 1st1** [comment]
@rome702 So did you get everything working?

**Comment by 1st1** [comment]
I'm closing this issue. Please feel free to re-open if you can share additional details.
