### ISSUE TITLE
Basic Usage help

### ISSUE THREAD

**Issue by jim256** [MagicStack/MagicPython#56]
I was just wondering if I could get some basic usage pointers?

After installing in VSCode, I'm unable to tell any difference in my Python file. Is there further configuration required?

**Comment by elprans** [comment]
VSCode v1.5.0 now uses MagicPython by default, so it's natural that you don't see the difference :-)  Perhaps we should update the README.

**Comment by jim256** [comment]
Oh, well that sure makes sense. So I'm guessing that I don't need to install the extensions at all then and could even uninstall it, correct?

**Comment by elprans** [comment]
I recommend keeping it still, so that you will receive updates, as VSCode version will likely lag somewhat.

**Comment by jim256** [comment]
Understood! Thanks so much for your help.
