### ISSUE TITLE
highlights for classes and their respective functions

### ISSUE THREAD

**Issue by srinath29** [MagicStack/MagicPython#57]
* **Editor name and version**: Visual Studio Code
* **Platform**: Windows
* **Color scheme**: Dark
* **MagicPython version**: 5.15

Hi,
This is more of like a enhancement. When I write code like 

```python
import os
currDir = os.path.dirname(os.path.abspath(__file__))

```
MagicPython should highlight _os_ with different colour as it is a module and _path_ also being a module, with the same colour in it and _dirname_ is function, so a different colour . It will be easy to identify the code like that. I understand from python perspective that all variables are just names to the objects lying in the memory. But a colour scheme will help understanding the code better.

Thank you

**Comment by vpetrovykh** [comment]
Thanks for your feedback. From the standpoint of the highlighter we aren't able to tell which names are actually modules and which are variables and functions. We treat built-ins differently by basically listing them all in the highlighter logic explicitly, but there's no generic way of doing this for all modules and functions.
In principle linters track modules and variable usage, so linter settings might be a better place to look for this kind of feature.

**Comment by ta32** [comment]
Surely it's better to highlight **all** function calls  whether they are from a module or built in. 
If you see a(), highlight a
can i reopen this issue?
