### ISSUE TITLE
MagicPython is incompatible with SublimeLinter

### ISSUE THREAD

**Issue by href** [MagicStack/MagicPython#6]
I tried this today and I noticed that SublimeLinter won't work if I use MagicPython. I'm guessing it has something to do with "Python" being a disabled package and it might well be a SublimeLinter bug.

I still thought I report it here. Maybe this is a known issue with a known workaround? :)

**Comment by 1st1** [comment]
I think you need to add `"magicpython": "python"` to the `"syntax_map"` in your SublimeLinter settings.

**Comment by href** [comment]
That did the trick. Thank you for your help!

**Comment by 1st1** [comment]
I created a PR for Sublime Linter -- https://github.com/SublimeLinter/SublimeLinter3/pull/352

**Comment by href** [comment]
Awesome, a better experience for the next person is what I was hoping for :)
