### ISSUE TITLE
isort not working with MagicPython

### ISSUE THREAD

**Issue by michaelaye** [MagicStack/MagicPython#60]
* **Editor name and version**: Atom 1.11.1
* **Platform**: macOS 10.11.6
* **Color scheme**:  UI: Atom Dark, Syntax Theme: Base16 Tomorrow Dark
* **MagicPython version**: 0.5.16
* **A sreenshot**: not possible for not working something. ;)
* **5-10 lines of surrounding code**: not a code issue

In the hope that you guys maybe know what needs to be done for fixing bh/atom-python-isort#26 : 
Basically, this packages calls the command line `isort` to resort the python imports in a clean manner. But it apparently doesn't know how to work with MagicPython.
I darkly remember a potential fix on putting somewhere in a config file the name of the MagicPython package to show either this package or the whole editor that MagicPython is now responsible for all Python related things?
Would be great to get `isort` working again, it helps a lot.
And thanks for the great syntax highlighting in MagicPython!

**Comment by 1st1** [comment]
I think the issue has been fixed in https://github.com/bh/atom-python-isort/commit/5e713c8fa7f8f3dff04c5cd7db8d2fe85e3a9e76. Anyways, isort is a separate package, so we can't really do anything in MagicPython to fix it.  Closing this issue.
