### ISSUE TITLE
Fail to download via Atom

### ISSUE THREAD

**Issue by agajardo100** [MagicStack/MagicPython#62]
* **Editor name and version**:   Atom 1.11.2
* **Platform**: Mac OSX 10.11.6
* **Color scheme**:  Atom Dark
* **MagicPython version**:  0.5.17
* **A screenshot**:  ![screen shot 2016-10-21 at 2 26 13 pm](https://cloud.githubusercontent.com/assets/14945184/19607820/60d15374-979a-11e6-8391-1959f33a4657.png)

* **5-10 lines of surrounding code**:
Unable to download https://www.atom.io/api/packages/magicpython/versions/0.5.17/tarball: getaddrinfo ENOTFOUND codeload.github.com codeload.github.com:443

**Comment by 1st1** [comment]
I'll close this issue since we can't really do anything about it :(
