### ISSUE TITLE
Incorrect highlighting of character class in regexp

### ISSUE THREAD

**Issue by elprans** [MagicStack/MagicPython#63]
* **Editor name and version**: Atom 1.11
* **Platform**: Linux
* **Color scheme**: Chromodynamics
* **MagicPython version**: 0.5.15
* **A sreenshot**: ![screenshot_20161107_150405](https://cloud.githubusercontent.com/assets/347119/20073755/78b48d12-a4fb-11e6-8ad7-0009e3242fb6.png)
* **5-10 lines of surrounding code**: `a = r'[[:alpha:]]'`

**Comment by vpetrovykh** [comment]
Not a bug. Python regular expressions do not have character class names like `[:alpha:]`, instead they use `\w` and similar ones. So the regular expression is actually highlighter correctly.
