### ISSUE TITLE
`async` is highlighted when its the name of an import

### ISSUE THREAD

**Issue by AlJohri** [MagicStack/MagicPython#64]
* **Editor name and version**: Sublime Text Build 3126
* **Platform**: Mac OS X El Capitan 10.11.1
* **Color scheme**: Monokai
* **MagicPython version**: unsure, latest? used package control on sublime
* **A sreenshot**:

![screen shot 2016-11-10 at 2 39 30 am](https://cloud.githubusercontent.com/assets/2790092/20168242/ed749c6a-a6ee-11e6-8976-9a4c7c192d7e.png)

* **5-10 lines of surrounding code**:

```python
#!/usr/bin/env python3

from craigslist.api.async import search
```

Thanks for making this package!

**Comment by elprans** [comment]
`async` is a soft-keyword since Python 3.5 and will become a reserved keyword in Python 3.7, so the name will have to change anyway.

**Comment by AlJohri** [comment]
Ah damn, I didn't realize that. Do you have any recommendations for writing code that is compatible with both sync and async styles together?

Get Outlook for iOS




On Thu, Nov 10, 2016 at 9:50 AM -0500, "Elvis Pranskevichus" <notifications@github.com> wrote:












async is a soft-keyword since Python 3.5 and will become a reserved keyword in Python 3.7, so the name will have to change anyway.

**Comment by elprans** [comment]
The `async` and `await` should no longer be used as variable names in code that is compatible with Python 3.7 or later. Rename those to something else.  The upcoming Python 3.6 will warn about the use of those names.

**Comment by 1st1** [comment]
Closing this issue, this isn't a bug.
