### ISSUE TITLE
Detection of colons in with statements and dict literals.

### ISSUE THREAD

**Issue by p0lm** [MagicStack/MagicPython#70]
Colons do not get detected as special characters when used inside a dict literal or at the block start of a `with` statement:

```python

d = { 'a': 'b' }

with open(__file__) as f:
  pass

```

In both cases I'd argue it needs to be detected as `punctuation`. For the `with` statement, I suggest also applying a `begin` label to the colon.

**Comment by 1st1** [comment]
Why do you need this?

**Comment by p0lm** [comment]
The syntax theme for Atom I'm working on uses a distinct color for both
assignment operators and punctuation, both it feels like it should wrap the
colon in when appropriate, as it does in all other cases I've come across
so far.

On 9 Dec 2016 23:23, "Yury Selivanov" <notifications@github.com> wrote:

Why do you need this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MagicStack/MagicPython/issues/70#issuecomment-266139662>,
or mute the thread

**Comment by vpetrovykh** [comment]
Fair enough. I'll update the highlighter for consistency. I'll add the following scopes:
- `punctuation.separator.dict.python` for `:` in dicts
- `punctuation.separator.slice.python` for `:` in slices
- `punctuation.separator.block.begin.python` for all other `:`, not already covered by more specific scopes (such as function and class definitions)
- `punctuation.separator.element.python` for `,` not already covered by more specific scopes in definitions and function calls (this will basically affect lists, tuples and dicts)

The changes will appear in the next release.

**Comment by p0lm** [comment]
Very nice. I personally hadn't even considered slices, but I'm very glad you've decided to include those as well, now I think of it.

**Comment by 1st1** [comment]
We've released `v0.6.2` with these changes in. Please test.

**Comment by vpetrovykh** [comment]
Upon further reflection, we've decided to rename `punctuation.separator.block.begin.python` into `punctuation.separator.colon.python` because `:` is used in blocks and in annotations. Attempting to detect that and distinguish one case from the other would complicate the highlighter grammar significantly. The other scopes remain as is.

**Comment by 1st1** [comment]
Closing the issue.
