### ISSUE TITLE
Error in ST3

### ISSUE THREAD

**Issue by bizoo** [MagicStack/MagicPython#71]
Error in console:
`no such context .fstring-illegal-multi-brace in Packages/MagicPython/grammars/MagicPython.tmLanguage`

Look like there's an include of  .fstring-illegal-multi-brace but it doesn't exists.

**Comment by 1st1** [comment]
Yeah, we know about this.  It's not that easy to fix (but certainly possible), because the rule is being generated from a template.  This doesn't prevent MP from working, right?

**Comment by vpetrovykh** [comment]
We've fixed that in the latest release.

**Comment by bizoo** [comment]
You're right, it doesn't prevent MP from working.
Thanks @vpetrovykh, no more messages in the console.
