### ISSUE TITLE
Async/Await syntax Python3.5

### ISSUE THREAD

**Issue by GinoHereIam** [MagicStack/MagicPython#72]
* **Editor name and version**: Visual Studio Code 1.9
* **Platform**: Linux
* **Color scheme**:
* **MagicPython version**:
* **A sreenshot**: 1.0.3
* **5-10 lines of surrounding code**: 
```python
async def check_environment(*envVars):
    """ environment check module """
    mapEnv = {}
    for env in envVars:
        try:
            mapEnv[env] = await os.environ[env]
        except IndexError:
            pass
    return mapEnv
```

Hi, 
with Python3.5 there is a new syntax defintion for Async/Await:
[https://www.python.org/dev/peps/pep-0492/](https://www.python.org/dev/peps/pep-0492/)
Would you mind to update MagicPython? I get a sytanx error for the example code. It's a great tool! :+1:  

Gino

**Comment by 1st1** [comment]
> I get a sytanx error for the example code.

**Comment by 1st1** [comment]
>  I get a sytanx error for the example code.

What do you mean? Do you have a Python SyntaxError exception when you run the code? Or that the code isn't highlighted properly?

**Comment by GinoHereIam** [comment]
Oh sorry, it's a `pylint` issue. I shot too fast. :D

**Comment by 1st1** [comment]
NP! Closing this one.
