### ISSUE TITLE
VS CODE (MACOSX)

### ISSUE THREAD

**Issue by yiyongooi** [MagicStack/MagicPython#74]
Hi, i have installed the ext and created a python project but there is no highlighting and any changes.

how do i activate the ext?

**Comment by elprans** [comment]
Hi @yiyongooi.  VS Code uses MagicPython by default already, so there would be no visible change when you install it.  However, you can keep the extension to receive updates to the highlighter in between VS Code updates.

**Comment by yiyongooi** [comment]
how do i set it such that it has similar highlighting effect like example.py from the main page?

**Comment by elprans** [comment]
You need the color scheme that supports all the scopes.  ``example.py`` uses chromodynamics.

**Comment by sohaeb** [comment]
I think this should be added to the READ.md in my opinion. I was really confused too and if I didn't come and search here I wouldn't have knew this.

Also, similar to @yiyongooi question regarding the color scheme. What are the steps that I need to follow to use chromodynamics color scheme ?
