### ISSUE TITLE
f-strings: Fix highlighting of `f` prefix

### ISSUE THREAD

**Issue by 1st1** [MagicStack/MagicPython#75]
GitHub highlights `r` and `f` prefixes differently:
<img width="161" alt="screen shot 2017-02-03 at 5 05 28 pm" src="https://cloud.githubusercontent.com/assets/239003/22610361/15e8c32e-ea33-11e6-9151-b21e0402c7e3.png">

**Comment by vpetrovykh** [comment]
The short answer is that it seems that the algorithm used by GitHub to decide colors based on scopes is treating the scope `string.quoted.single.python` as more important than `storage.type.string.python`. I think this is largely beyond our control as a highlighter package, but an issue with the color scheme implementation.
