### ISSUE TITLE
Python syntax highlight error

### ISSUE THREAD

**Issue by aeschli** [MagicStack/MagicPython#77]
_From @cg-cnu on March 17, 2017 7:25_

- VSCode Version: Version 1.10.2
- OS Version: CentOS Linux release 7.1.1503 (Core) 

![pythonprint](https://cloud.githubusercontent.com/assets/2767425/24033029/e6764432-0b10-11e7-96d1-5d81afcdd061.png)

Python print statement is not showing proper syntax highlighting.
I have the suggested python [extension](https://github.com/DonJayamanne/pythonVSCode) enabled as well.

_Copied from original issue: Microsoft/vscode#22779_

**Comment by 1st1** [comment]
This is a color schema issue. The following scopes are assigned to the `print` token:

```
source.python 
meta.function-call.python 
support.function.builtin.python
```
