### ISSUE TITLE
Incorrect highlighting of list brackets

### ISSUE THREAD

**Issue by tfeldmann** [MagicStack/MagicPython#8]
![bildschirmfoto 2015-10-20 um 15 17 13](https://cloud.githubusercontent.com/assets/385566/10608098/c7134fda-773d-11e5-84a5-62528602f771.png)
See the screenshot: The left bracket is blue and the right bracket white.

**Comment by 1st1** [comment]
Interesting, thanks for reporting.  What color scheme are you using?

**Comment by tfeldmann** [comment]
No problem. I'm using the Tomorrow-Night-Eighties color scheme

**Comment by 1st1** [comment]
Fixed in v0.4.22 (should be updated in Package Control in a bit). Thanks!
