### ISSUE TITLE
Atom/Hydrogen plugin: SyntaxError when creating multi-line dictionaries

### ISSUE THREAD

**Issue by onewhaleid** [MagicStack/MagicPython#80]
I get an error in Hydrogen when I try to run the first line of a multi-line dictionary definition.

I opened an issue with Hydrogen, but they told me that code folding is all managed within the `python-language` package.

The original issue is here:
https://github.com/nteract/hydrogen/issues/724#issuecomment-296287013

* **Editor name and version**: Atom : 1.16.0
* **Platform**: Win7 x64
* **Color scheme**: seti-classic-syntax 0.5.0
* **MagicPython version**:1.0.9
* **A sreenshot**:
![image](https://cloud.githubusercontent.com/assets/11261876/25296332/173cd50a-272b-11e7-914f-58fc52eadf53.png)

**Comment by 1st1** [comment]
We're waiting for details on what exact scopes hydrogen expects to see there, as this is the only thing that MagicPython is in control of. FWIW MagicPython uses the same scopes for both dicts with whitespace and without.

**Comment by vpetrovykh** [comment]
@onewhaleid can you please update the MagicPython package to 1.0.11 and check if the issue still persists? For me the code folding issue seemed to be resolved with the newer MagicPython grammar (Atom 1.16.0 on Linux), but I'm not sure whether that also resolves the issue with Hydrogen.

**Comment by onewhaleid** [comment]
@vpetrovykh the problem is fixed, but only if the closing grouping symbol has matching indentation.

This works:
```
x = {
    'a': 1,
    'b': 2,
    'c': 3,
    'd': 4,
    'e': 5,
    'f': 6,
    'g': 7,
    'h': 8,
    'i': 9,
    'j': 10
    }
```
But this fails (and this is the preferred style for `YAPF`):
```
x = {
    'a': 1,
    'b': 2,
    'c': 3,
    'd': 4,
    'e': 5,
    'f': 6,
    'g': 7,
    'h': 8,
    'i': 9,
    'j': 10
}
```
```
File "<ipython-input-33-086813cd33d2>", line 11
    'j': 10
           ^
SyntaxError: unexpected EOF while parsing
```

I am using `MagicPython 1.0.11` and `Hydrogen 1.19.1`

**Comment by vpetrovykh** [comment]
```
x = {
    'a': 1,
    }
```
folds to
```
x = {...
```
and
```
x = {
    'a': 1,
}
```
folds to
```
x = {...
}
```
by **both** MagicPython and language-python for me (Atom 1.16.0 on Linux). So as far as I can tell the folding works out identically. 

When I tried using Hydrogen on the problematic snippet I got the same syntax error regardless of whether MagicPython or default Python highlighter was used. @onewhaleid  are you able to get different results with the default Python package?

**Comment by onewhaleid** [comment]
I get the same syntax error with `MagicPython` and `language-python`.

**Comment by vpetrovykh** [comment]
It looks like it's a general Atom issue, rather then a language-specific one. Atom doesn't have a good way to customize code folding, so anything that relies on that mechanism is going to have some problems. See https://github.com/atom/first-mate/issues/48 and https://github.com/atom/atom/issues/11838.
