### ISSUE TITLE
Docstrings in sublime

### ISSUE THREAD

**Issue by michaelboulton** [MagicStack/MagicPython#81]
* **Editor name and version**: Sublime 3 3126
* **Platform**: Linux
* **MagicPython version**: 1.0.9

In sublime, normally if you type 3 double quotes (`"""`) then it will figure out that you're trying to create a docstring and begin highlighting as such, but more importantly it won't think that you're creating 2 separate strings next to one another and create a 4th quotation mark. With MagicPython installed, when you enter 3 double quotes it does enter the 4th one.

As an example, if you want to enter a docstring for a class then enter a triple quotation mark and press enter, this is what it normally looks like:

```python
class X:
    """

```
and this is what it's like with MagicPython:
```python
class X:
    """
    "
```
It doesn't seem do to this in visual studio code, so I think it's specific to the sublime version.

**Comment by 1st1** [comment]
Fixed in `1.0.10`. Thanks for reporting this!
