### ISSUE TITLE
(Some?) keywords not highlighted when surrounded by text

### ISSUE THREAD

**Issue by zgoda** [MagicStack/MagicPython#84]
* VS Code 1.12.2
* **Platform**: Ubuntu 16.04 x86_64
* **Color scheme**: Base16 Dark Tomorrow
* **MagicPython version**: 1.0.10
![zrzut ekranu z 2017-05-24 10-48-49](https://cloud.githubusercontent.com/assets/141999/26397220/d8a640a6-4075-11e7-9329-a84ef903d726.png)

`and` and `not` are not highlighted above, although these keywords are highlighted properly when there is no text after them:
![zrzut ekranu z 2017-05-24 11-42-16](https://cloud.githubusercontent.com/assets/141999/26397344/45faa3e0-4076-11e7-8d08-c3baa0d2954f.png)
![zrzut ekranu z 2017-05-24 11-42-43](https://cloud.githubusercontent.com/assets/141999/26397354/4dc83786-4076-11e7-8dc2-b81236b4c6c4.png)

**Comment by vpetrovykh** [comment]
Since GitHub is using our library to highlight code, we can quickly test how a particular snippet of it gets highlighted right here:
```python
# the original problematic code
if axisid in (1, 2) and value != 0 and not self.closing:
# compared to
if value != (0, 0) and value[0] != 0 and not ...
```
As you can see, the keywords get highlighted correctly in the snippets. I suspect that the plugin that reformats the code to have fancy `≠` as opposed to `!=` can interfere with the highlighter by consuming or altering some tokens.

**Comment by zgoda** [comment]
In my example `not` is nowhere near ligatures (the fancy stuff). Moreover, `and` is highlighted properly if there is no text tokens **after** it, not before where ligature is placed. Better, placing a colon after problematic keyword makes it highlighted right:

![zrzut ekranu z 2017-05-25 09-31-58](https://cloud.githubusercontent.com/assets/141999/26440528/090b0a80-412d-11e7-90dd-665e64e41770.png)

Example line without ligatures:

![zrzut ekranu z 2017-05-25 09-18-42](https://cloud.githubusercontent.com/assets/141999/26440146/48c6a03c-412b-11e7-86d0-a844c4e94a38.png)

FWIW, the same line in SublimeText looks exactly the same so I'd rather suspect a problem with TextMate rules (either in highlighter rules itself or in rule processor, IDK how it's done exactly):

![zrzut ekranu z 2017-05-25 09-20-53](https://cloud.githubusercontent.com/assets/141999/26440205/8cd4e982-412b-11e7-81a7-b22889cbacdb.png)

BTW, support for ligatures is built-in in font rendering engine used by VS Code so there's no "plugin interference" here. Nothing changes if I turn off ligatures in editor settings (`editor.fontLigatures` in settings.json) or use font that does not have ligatures.

**Comment by elprans** [comment]
This is a color scheme issue.  See below for how the same snippet is rendered in VSCode for me:

![screenshot_20170525_093723](https://cloud.githubusercontent.com/assets/347119/26452485/21a37b3a-412e-11e7-892a-7a0c0b881953.png)
