### ISSUE TITLE
Type 'long' receives no color (str and int do)

### ISSUE THREAD

**Issue by gandhis1** [MagicStack/MagicPython#85]
![image](https://cloud.githubusercontent.com/assets/21064086/26807252/71d163ee-4a23-11e7-9e8c-5b9281737790.png)

In this screenshot, the str type receives blue highlighting in VS Code Monokai, but the long type does not. Seems a bit odd, is this intended behavior?

**Comment by 1st1** [comment]
`long` is a builtin in Python 2 but isn't one in Python 3.  Yet MagicPython assigns `variable.legacy.builtin.python` scope to all Python 2 only builtins, so you can customize your color scheme to highlight them if you need to.
