### ISSUE TITLE
Redefined keyword in function name

### ISSUE THREAD

**Issue by kiddick** [MagicStack/MagicPython#88]
![image](https://user-images.githubusercontent.com/9250239/26940366-0d07d120-4c83-11e7-82ad-6265ec2e2540.png)

As you can see I am redefining `list` keyword in name of function. And this is still considered as keyword. But it doesn't make sense. Is it by design?

I know that is bad pattern to redefine keyword, but it is matter of user choice.
Should we disable that great feature and don't colorize keywords in function definition as standard plugin do.

**Comment by 1st1** [comment]
Yes, it's by design. MagicPython highlights `list` as a builtin so that you know that you are shadowing it.

**Comment by kiddick** [comment]
@1st1 but I have linters for that. Is it possible to have flag in config to disable that behavior?

**Comment by 1st1** [comment]
Unfortunately, no, syntax highlighters don't have preferences/options. It is theoretically possible, but will require a lot of time to get it working for all editors that MP supports. Keep in mind that MP is used by github to highlight Python code, and not all users have linters.
