### ISSUE TITLE
"super()" formatting

### ISSUE THREAD

**Issue by tfeldmann** [MagicStack/MagicPython#9]
The super() statement seems seems not be distinguished from other functions and has blue parens. This could be better.
See the screenshots (Sublime Text, tomorrow night eighties theme)

1. MagicPython

![bildschirmfoto 2015-10-20 um 16 23 20](https://cloud.githubusercontent.com/assets/385566/10610350/b4520684-7747-11e5-942e-705e94dee4dd.png)

2. Default Python3 highlighter

![bildschirmfoto 2015-10-20 um 16 24 49](https://cloud.githubusercontent.com/assets/385566/10610356/bc397990-7747-11e5-918f-c320688034c6.png)

**Comment by 1st1** [comment]
Hm.  We scope "super" with "meta.function-call.python, support.function.builtin.python" scopes, and parens with "meta.function-call.arguments.python, meta.function-call.python, punctuation.definition.arguments.begin.python".  It looks like that's just how "Tomorrow Eighties" styles those.  

This is Tomorrow Eighties with Python syntax:
<img width="706" alt="screen shot 2015-10-20 at 10 44 37 am" src="https://cloud.githubusercontent.com/assets/239003/10610866/a25adb7a-7717-11e5-90d5-c60b06e4a6ed.png">

This is Tomorrow Eighties with MagicPython syntax:
<img width="706" alt="screen shot 2015-10-20 at 10 44 45 am" src="https://cloud.githubusercontent.com/assets/239003/10610867/a27b39c4-7717-11e5-9475-c76d15c963ab.png">

And this is our scheme with MagicPython:
<img width="706" alt="screen shot 2015-10-20 at 10 44 56 am" src="https://cloud.githubusercontent.com/assets/239003/10610868/a2849406-7717-11e5-91c7-5533a739b816.png">

**Comment by tfeldmann** [comment]
I'm sorry, the second screenshot is from "Python 3" package (https://packagecontrol.io/packages/Python%203).

**Comment by 1st1** [comment]
Alright, this should be fixed in v0.4.25. See bff4e71412abea1699dbb51215fbdcba60c67df2 for details. Thanks!
