### ISSUE TITLE
Class definition highlight error 

### ISSUE THREAD

**Issue by westminsterabi** [MagicStack/MagicPython#90]
Function definitions don't highlight within class definitions. :( 

```python
def ts_to_epoch(timestamp):
    pattern = '%Y-%m-%d %H:%M:%S'
    epoch = int(time.mktime(time.strptime(timestamp, pattern))
    return epoch


class DBManager(object):

    def constructor():
        self.handle_disconnect()
```

Atom 1.16.0 
Mac OS X 10.12.5
Dark One
MP 1.0.10

![image](https://user-images.githubusercontent.com/24930199/27446135-148bfdd0-5742-11e7-999b-938015b40e56.png)

**Comment by 1st1** [comment]
That's because you have an unclosed paren at the `epoch = int` line:

`epoch = int(time.mktime(time.strptime(timestamp, pattern))`

should be

`epoch = int(time.mktime(time.strptime(timestamp, pattern)))`

**Comment by westminsterabi** [comment]
ahhhh thank you!
