### ISSUE TITLE
Scons files support (python 2.x based presently)

### ISSUE THREAD

**Issue by ensiform** [MagicStack/MagicPython#91]
Looking to see if you or any of the other python extensions could add SCons highlighting support with your python plugin.

It's a builder tool that users write their build scripts in Python2 and files are generally labeled as: `SConscript` `SConstruct` or `SConscirpt.anythinguserwants` from what I have seen.

I'm not sure if it would be better to have a separate extension/language which requires one of the Python vscode python libs as a dependency or just integrate it (not familiar with the process of building languages in vscode myself presently)

**EDIT:** Seems one can add paths manually to user settings that redirects to a specific type, however it might be nice if this could be automatically included.

**Comment by 1st1** [comment]
MagicPython should already highlight "SConstruct, Sconstruct, sconstruct, SConscript" files. What's the editor?

**Comment by ensiform** [comment]
VSCode, it wasn't doing it for me. Hmm

**Comment by 1st1** [comment]
Perhaps it's an issue of VSCode then. Can you open a bug there?

**Comment by 1st1** [comment]
I'm closing this one, feel free to reopen.
