### ISSUE TITLE
"The Travis CI build failed"

### ISSUE THREAD

**Issue by tennyson-mccalla** [MagicStack/MagicPython#93]
Tried to make [a pull request](https://github.com/MagicStack/MagicPython/pull/92) but got [this error](https://travis-ci.org/MagicStack/MagicPython/builds/255363735?utm_source=github_status&utm_medium=notification).

I'm not sure what if anything I'm to to do at this point. Maybe @1st1 can guide me from here?

**Comment by 1st1** [comment]
Thanks for reporting this! Should be fixed now.
