### ISSUE TITLE
Colorize classes and packages

### ISSUE THREAD

**Issue by alete89** [MagicStack/MagicPython#97]
* **Editor name and version**: Visual Studio Code Insiders
* **Platform**: Windows 10 x64
* **Color scheme**: Dark+, Monokai, or any
* **MagicPython version**:  1.0.11

Hi. First things first, thanks for this project. It's awesome.
Second. I'm aware that MagicPython only "clasify" the code and then color schemes are applied.
Now, how can I know if a syntax is being "clasified" by MagicPython but my scheme isn't changing it's color?

Or specifically, does Magic Python support colorizing classes when I invoke them in code?

![vs](https://user-images.githubusercontent.com/4999277/28595681-4df49030-716b-11e7-8908-f4a646bd0395.png)

What I love: yellow-ish in function definitios.
What I would like: classes in lightblue (see QApplication or MainWindow in main() ) and packages highlighted like VS (purple).

If this isn't actually an issue, everything works as intended then I apologize. If there is a workaround to achieve what I'm looking for, I will be appreciated

**Comment by vpetrovykh** [comment]
Thanks for your comments! It's nice to hear you like MagicPython.

Here's a short answer for highlighting classes and imports: it cannot be done with only a syntax highlighter. To know whether something is a class, or an imported entity, or something else a more general code/variable type analysis is necessary which is beyond the ability of a humble regular expression (the syntax highlighter is effectively a very complex regular expression with only very minor enhancements). So this is beyond the scope of *syntax*. 

I would think that some other plug-in could perform code analysis and add more "classes" to the code for the color scheme to work with. I don't have a more specific suggestion, though.

**Comment by alete89** [comment]
Thank you for your reply, it has been clarifying.
